### ISSUE TITLE
Command `commentTranslate.replaceSelections` more convenient - unnecessary window, useful context menu

### ISSUE THREAD

**Issue by lukaszpolowczyk** [intellism/vscode-comment-translate#102]
Please make it so that `commentTranslate.replaceSelections` does not ask for confirmation of the selected language, but automatically translates to the language set in the settings.
Now my language is marked as default, but the language selection list appears anyway.
This is unnecessary.

I would also like `commentTranslate.replaceSelections` to appear with the context menu of the selected text in the editor.

**Comment by intellism** [comment]
Thanks for the feedback. There has been similar feedback before, and it will be adjusted to user configuration later.

**Comment by intellism** [comment]
v2.2.0 supported
