### ISSUE TITLE
BUG: v2.2.0 会多显示一个翻译提示。

### ISSUE THREAD

**Issue by shanyuhai123** [intellism/vscode-comment-translate#104]
在 v2.1.0 正常显示  
![image](https://user-images.githubusercontent.com/27122409/173980362-9d910670-b9ee-4c78-8eb1-e461a50cf68e.png)

在 v2.2.0 中会多显示一条
![image](https://user-images.githubusercontent.com/27122409/173980504-d64a9989-4eec-4c3e-b1fe-4930ab1153e5.png)

**Comment by intellism** [comment]
谢谢反馈，v2.2.0新增实验功能，翻译其他插件的Hover Content。部分不需要翻译的区域识别不精准，后面持续优化修复中。
如果对你有影响，可以使用配置关闭  `commentTranslate.hover.content`: 开启/关闭翻译悬停内容。
Hover的场景非常多，可能与其他插件有冲突，也欢迎继续提供应用场景。

![ezgif-3-a3aee6291d](https://user-images.githubusercontent.com/442894/173977969-61ea4d94-eba8-4f2a-b3dd-cd47610ebe10.gif)
