### ISSUE TITLE
[Feature Request] 能否添加一个手动关闭翻译窗口的选项

### ISSUE THREAD

**Issue by a1398394385** [intellism/vscode-comment-translate#105]
很多时候, 翻译窗口不能完全展示需要翻译的内容, 这个时候就需要去翻译窗口进行下拉操作. 但是翻译窗口的关闭逻辑是鼠标移动就自动关闭, 这样就会出现下图中的这种情况, 并不是很人性化. 也许可以添加一个选项, 允许用户手动关闭翻译窗口, 比如鼠标点击其他区域时关闭.
![VScode翻译截图](https://user-images.githubusercontent.com/44491763/173985599-453a3ae6-8823-4600-a31b-3f4de198938c.gif)

**Comment by intellism** [comment]
翻译窗口是vscode默认行为，插件不可以控制显示与关闭。

**Comment by a1398394385** [comment]
😭

**Comment by intellism** [comment]
v2.2.2 调整了Hover Overlay的位置，更容易到浮层上了。 
副作用是，会更多覆盖被翻译内容，不方便做比较.

![image](https://user-images.githubusercontent.com/442894/176353692-d12a2e74-133a-4439-9654-c5134a6820db.png)

**Comment by a1398394385** [comment]
VScode 在1.72的版本更新中对浮窗的展示和隐藏逻辑进行了更新, 只要鼠标在朝着浮窗移动, 浮窗就不会自动隐藏, 详情可见版本更新公告 [September 2022 (version 1.72) Improved hover](https://code.visualstudio.com/updates/v1_72#_improved-hover) 😃

https://user-images.githubusercontent.com/44491763/194699143-4882d6d6-04ec-48a3-8a99-b86d1d7ccc96.mp4

**Comment by intellism** [comment]
> VScode 在1.72的版本更新中对浮窗的展示和隐藏逻辑进行了更新, 只要鼠标在朝着浮窗移动, 浮窗就不会自动隐藏, 详情可见版本更新公告 [September 2022 (version 1.72) Improved hover](https://code.visualstudio.com/updates/v1_72#_improved-hover) 😃
> 
>  Editor.hover.after.mp4

赞，这就是之前做的 hover nearShow。  看样子这个功能可以废弃了。  可以通过`commentTranslate.hover.nearShow`关闭掉之前的行为了。

**Comment by leiyunkang7** [comment]
mark, 遇到同样的问题
