### ISSUE TITLE
Google Translate: Tld cn 不工作

### ISSUE THREAD

**Issue by lusson-luo** [intellism/vscode-comment-translate#109]
问题：
本机浏览器 translate.google.com 不能访问，导致翻译插件使用失败，访问 translate.google.cn 成功。
将插件 api 地址改为  translate.google.cn 不工作。

插件版本：2.2.1
设置：Tld cn
<img width="797" alt="image" src="https://user-images.githubusercontent.com/19859400/175968033-f4c71a0a-2561-46cf-9f13-3f77642ef91c.png">
还是有错误
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/19859400/175968303-44673b01-809d-417b-85f0-3dc51ae9816f.png">

**Comment by intellism** [comment]
检查下是否有代理。还有可能是不是公司局域网，这个时段访问过多了。
我本地测试是可以的
![image](https://user-images.githubusercontent.com/442894/176069976-e356e2b5-46dc-4933-a37f-f0098b323fc7.png)

**Comment by lusson-luo** [comment]
> 还有可能是不是公司局域网，这个时段访问过多了。
> 我本地测试是可以的

我的问题是 Tld 不生效，设置 tid 为 cn 后，应该通过 translate.google.cn api 访问，日志显示还是用 translate.google.com
![image](https://user-images.githubusercontent.com/19859400/176085118-36d0d343-a837-4988-a68d-ea9e4d1e9d7f.png)
![image](https://user-images.githubusercontent.com/19859400/176085183-bc4f3a9b-aa96-4721-84e1-67e092280d26.png)

**Comment by intellism** [comment]
检查下，你设置的是 “用户”还是“工作区配置”。  工作区会优先的。
![image](https://user-images.githubusercontent.com/442894/176104866-e3d220e8-35e8-4d48-b66f-46cefe1b87ed.png)

**Comment by lusson-luo** [comment]
> 检查下，你设置的是 “用户”还是“工作区配置”。 工作区会优先的。 ![image](https://user-images.githubusercontent.com/442894/176104866-e3d220e8-35e8-4d48-b66f-46cefe1b87ed.png)

对，我设置的是用户，工作区没有设置，还是 com
