### ISSUE TITLE
aa

### ISSUE THREAD

**Issue by tenbukilloneperson** [intellism/vscode-comment-translate#11]
这个东西 怎么用啊  为什么我装上了没有效果。是需要什么配置吗

**Comment by intellism** [comment]
不需要任何配置就可以使用的，请检查下是否安装成功。
安装成功后，会注册命令和状态栏，如下图:
![image](https://user-images.githubusercontent.com/442894/58851354-fc881700-86c4-11e9-9bd7-2c0564061eca.png)
