### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by yungchunw** [intellism/vscode-comment-translate#111]
- Issue Type: `Performance`
- Extension Name: `comment-translate`
- Extension Version: `2.2.4`
- OS Version: `Darwin arm64 21.3.0`
- VS Code version: `1.68.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/6v/wzt_ggl95mz0gtg02rwx1qh40000gn/T/intellsmi.comment-translate-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by intellism** [comment]
#130 类似，v2.3.0 已修复
