### ISSUE TITLE
CPU负载

### ISSUE THREAD

**Issue by Shu-Ying** [intellism/vscode-comment-translate#112]
目前这个扩展有着过高的CPU负载，这会导致我的骨架和提示框无法显示

**Comment by intellism** [comment]
麻烦提供下更多信息。在什么场景下cpu负载过高？

**Comment by Shu-Ying** [comment]
> 麻烦提供下更多信息。在什么场景下cpu负载过高？

目前有三种：1.每次打开VCode 2.首次激活扩展 3.首次新的翻译（是新的，旧的似乎有翻译记录）

**Comment by intellism** [comment]
> 

是cpu负载高，还是启动时翻译有延迟？  翻译插件不是必须的，所以启动时间比较靠后。
#94

**Comment by Shu-Ying** [comment]
> > 
> 
> 是cpu负载率高，还是启动时翻译有延迟？ 翻译插件不是必须的，所以启动时间比较靠后。 #94
是异常高，我正常的占用率为10%，一旦翻译或者首次启动就会到达40%。当然我觉得这不是问题，主要只要翻译之后，就会把提示框和骨架卡没，必须要等一阵子才会恢复提示框和骨架

**Comment by intellism** [comment]
"只要翻译之后，就会把提示框和骨架卡没，必须要等一阵子才会恢复提示框和骨架"

这个是什么意思？

麻烦提供下更多信息。

**Comment by Shu-Ying** [comment]
> "只要翻译之后，就会把提示框和骨架卡没，必须要等一阵子才会恢复提示框和骨架"
> 
> 这个是什么意思？
> 
> 麻烦提供下更多信息。

我录制个视频，大佬过目

链接：https://pan.baidu.com/s/167fsvGx4JNikfCeQwtAjuA?pwd=5h9a 
提取码：5h9a

**Comment by intellism** [comment]
> 

谢谢反馈，看了视频发现问题了。之前没考虑过源文件超多行的情况，为了分析注释，使用了textmate，对超多行的处理没做优化，后面看看做一些限制和优化。
