### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by baboon-king** [intellism/vscode-comment-translate#113]
- Issue Type: `Bug`
- Extension Name: `comment-translate`
- Extension Version: `2.2.4`
- OS Version: `Darwin arm64 22.0.0`
- VS Code version: `1.69.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 86,
		"activateCallTime": 1,
		"activateResolvedTime": 13,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "intellsmi.comment-translate",
				"_lower": "intellsmi.comment-translate"
			},
			"activationEvent": "onStartupFinished"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

![image](https://user-images.githubusercontent.com/63645337/179693807-74cf7dd6-8bf7-42c2-8151-15372a695607.png)

**Comment by intellism** [comment]
你的意思是  hover响应时间过长吧？  

这个是因为 #84 对其他hover对象的内容进行翻译，需要等待其他所有插件的hover返回后，再翻译，所以时间比较长，但是对cpu的影响比较小，插件都做了hover复用的。

可以通过 (commentTranslate.hover.content: 开启/关闭翻译悬停内容) 关闭后看看。
![image](https://user-images.githubusercontent.com/442894/179700411-17f9394f-3682-4b09-923a-e96a0d411d7d.png)

**Comment by baboon-king** [comment]
多谢你的答复！
