### ISSUE TITLE
多行注释翻译的合并问题

### ISSUE THREAD

**Issue by Macarion** [intellism/vscode-comment-translate#117]
对于以\*号开头的多行注释，好像是先对每行进行翻译然后再合并结果。
能不能先合并注释并剔除其中的\*号，然后再进行翻译呢？
VS Code版本：1.69.2
Comment Translate版本：2.2.4
![image](https://user-images.githubusercontent.com/52400286/181919038-2acb5340-fdaa-4b69-9273-46bee34928f1.png)

**Comment by intellism** [comment]
已经剔除了，可以查看下 输出日志里面真实的翻译文本。
保持行数一致性，显示的时候故意还原的。

建议开启多行合并，跨行如果是一个句子，就会合并一行显示了。
commentTranslate.multilineMerge: 合并多行注释

**Comment by Macarion** [comment]
开启合并多行注释选项了，输出日志里原文本前也确实带有*号，这个应该是vs code对多行注释的支持不好，貌似从api里取出来的内容就是带有*号的。
不过保持行数不变这条的确是我考虑不周。
