### ISSUE TITLE
希望能够翻译提示信息

### ISSUE THREAD

**Issue by A-kirami** [intellism/vscode-comment-translate#118]
比如警告和报错

![image](https://user-images.githubusercontent.com/66513481/182845667-0e410acd-eb08-48dc-9ef2-023728e8b298.png)

**Comment by intellism** [comment]
收到，可以支持，就是原始信息不能屏蔽，原始信息和翻译信息都会显示，比较影响阅读。

**Comment by A-kirami** [comment]
感谢回复，我觉得可以支持开关就好了。
顺便，我同时在使用 `Code Translate` 这个插件，然后就出现了 `Comment Translate` 把 `Code Translate` 的内容又翻译一遍的情况，想问问有没有什么办法能够将它排除
![image](https://user-images.githubusercontent.com/66513481/182865153-a524e403-3558-4022-9054-190618809f35.png)

**Comment by intellism** [comment]
commentTranslate.hover.content: 开启/关闭翻译悬停内容
这个可以关闭
