### ISSUE TITLE
为什么翻译出来一堆乱码？

### ISSUE THREAD

**Issue by everdom** [intellism/vscode-comment-translate#119]
全是类似这样的结果是为啥？改用其他翻译源也是这样
`
[Comment Translate]        |    [Google](vscode-file://vscode-app/c:/Users/Administrator/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)%20Define%20%22fil_runout%3A0%22%20below%20to%20disable%20the%20sensor%20handling%20on%20the%20TFT.%0A%23%20%20%202)%20Configure%20the%20sensor%20in%20the%20firmware%20of%20your%20mainboard.%0A%23%20%20%203)%20Add%20M75%20to%20%22start_gcode%22%20and%20M77%20to%20%22end_gcode%22%20of%20the%20TFT%20(or%20your%20slicer).%0A%23%23%23%23%20Filament%20Runout%20Sensor%0A%23%20Select%20the%20type%20of%20filament%20runout%20sensor%20and%20its%20default%20enabled%2Fdisabled%20state.%0A%23%20%20%20Options%3A%20%5BNormal%20Disabled%3A%200%2C%20Normal%20Enabled%3A%201%2C%20Smart%20Disabled%3A%202%2C%20Smart%20Enabled%3A%203%5D%0A%23%23%23%23%20Inverted%20Filament%20Runout%20Sensor%20Logic%0A%23%20The%20sensor%20uses%20an%20inverted%20logic.%0A%23%20Disabl
`

**Comment by everdom** [comment]
![2022-08-08 16 15 55](https://user-images.githubusercontent.com/760383/183372120-f044888d-af57-49d7-a894-4daae621f3e9.png)

**Comment by intellism** [comment]
hover提示是markdown格式的，在翻译内容里面有  ) ]  等markdown字符，会出现这种情况。

**Comment by intellism** [comment]
v2.3.0 已修复
