### ISSUE TITLE
经常出现无法翻译的情况？

### ISSUE THREAD

**Issue by jiejieTop** [intellism/vscode-comment-translate#12]
大神你好啊~很荣幸能使用这个插件，但似乎遇到了点问题......
如题，本来原先翻译是正常的，但用着用着就出现下图情况：
![image](https://user-images.githubusercontent.com/41819258/59001953-34b56400-8843-11e9-87f0-2d1d4eab7c78.png)

ps：已确认网络状况良好

**Comment by jiejieTop** [comment]
是不是被墙了？可能墙内用户太多

**Comment by intellism** [comment]
#6 是被google的翻译服务拒绝服务了，是因为同一局域网内使用的用户使用太多了。 下一个版本会提供配置，支持自行配置翻译授权api。

**Comment by intellism** [comment]
当然你还可以想办法变换ip.(如代理、vpn等)

**Comment by jiejieTop** [comment]
> #6 是被google的翻译服务拒绝服务了，是因为同一局域网内使用的用户使用太多了。 下一个版本会提供配置，支持自行配置翻译授权api。

很棒的项目，赞赞赞，支持，nice

**Comment by lifetin** [comment]
> #6 是被google的翻译服务拒绝服务了，是因为同一局域网内使用的用户使用太多了。 下一个版本会提供配置，支持自行配置翻译授权api。
![44](https://user-images.githubusercontent.com/10474968/59564288-7fbb4c80-9077-11e9-9560-6551b7f9b241.png)


一直在等啊.我这也经常不出来内容.
建议你用国内的做个备用得了,国内的都一些机器翻译,现在也都不差了毕竟只是看个大概意思.
百度有机器翻译,阿里云也有.然后增加自己的appkey配置.或是共用的配置.
