### ISSUE TITLE
wsl环境下,配置了http代理后无法使用

### ISSUE THREAD

**Issue by liupingquan** [intellism/vscode-comment-translate#120]
vscode在配置了http代理后, vscode-comment-translate 似乎不能正确的使用代理.
`  "http.proxy": "http://127.0.0.1:10880" ` 

wsl环境下vscode访问拓展库的时候,可以正确连接到windows主机的代理, 但是vscode-comment-translate似乎访问的是wsl的本地ip, 无法连接到windows主机的代理.

**Comment by liupingquan** [comment]
请问使用谷歌翻译的时候, 有什么建议呢?

**Comment by intellism** [comment]
没有做过  代理的支持，  空了我研究下。。 也欢迎PR或提供方案

**Comment by dzylikecode** [comment]
@intellism  原来是因为代理的缘故吗, 不用代理能工作吗, 用其他翻译

**Comment by intellism** [comment]
google  cn、bing应该是可以直接使用的。
baidu目前接口升级了，目前用不了。

---
也建议使用aliyun翻译，，注册一个账号填写key，每个月有免费的量，够日常使用。
当然也可以安装其他三方翻译源
