### ISSUE TITLE
希望可以中英对照，那就完美了

### ISSUE THREAD

**Issue by lulu-sk** [intellism/vscode-comment-translate#122]
举个例子
//store this value for errorChecking at a later time 
//(to make sure a rigidbody isn't added AFTER colliderWatcher is initialized)
//储存这个值，以便在以后的时间里进行错误检查 
//（以确保刚体不会在colliderWatcher初始化之后被添加）。

**Comment by intellism** [comment]
源码文件里面，已经有原始被翻译内容了，已经可以参考对照了。
