### ISSUE TITLE
切换每个 translate source都不能翻译

### ISSUE THREAD

**Issue by Linefate** [intellism/vscode-comment-translate#127]
每个 translate source都不能翻译，求求

-----------
## Switch translate source to 'Bing'.

[Start translate]: Use 'Bing' translate source
[Start translate]: Use 'Bing' translate source
[Bing]: request error:
 RequestError: read ECONNRESET 
Try again later or change translate source.{"name":"RequestError","code":"ECONNRESET","timings":{"start":1662276250502,"socket":1662276250507,

------------------------------
## Switch translate source to 'Google'.

[Start translate]: Use 'Google' translate source
[Start translate]: Use 'Google' translate source
[Start translate]: Use 'Google' translate source
[Google]: request error:
 RequestError: read ECONNRESET 
 Try again later or change translate source.{"code":"ECONNRESET","timings":{"start":1662276323385,"socket":1662276323390,"lookup":1662276323390,"connect":1662276323390,"secureConnect":1662276323625,"upload":1662276323625,"response":1662276323748,"end":1662276323749,"error":1662276323750,"phases":{"wait":5,"dns":0,"tcp":0,"tls":235,"request":0,"firstByte":123,"download":1,"total":365}}
 
 -------------------
 ## Switch translate source to 'Baidu'.

[Start translate]: Use 'Baidu' translate source
[Start translate]: Use 'Baidu' translate source
[Start translate]: Use 'Baidu' translate source
[Baidu]: request error:
 [object Object] 
 Try again later or change translate source.{"errno":998,"errmsg":"未知错误","query":">  \\- Removed conditional which fell back to 'setTimeout' when the\r\t\\\n>  environment doesn't have DOM\\. This appears to be an old polyfill used\r\t\\\n>  for test environments and we don't use it any more\\.\r\t\\\n>  \\- Fixed type definitions around the callbackID to be more accurate in\r\t\\\n>  the scheduler itself, and more loose in the React code\\.\r\t\\\n>

**Comment by intellism** [comment]
是使用了代理工具?

**Comment by intellism** [comment]
也可以尝试下，安装插件外翻译源。
![image](https://user-images.githubusercontent.com/442894/188570351-9100573b-4144-4069-b5cc-0686bc6d81ca.png)

**Comment by Linefate** [comment]
突然就可以翻译了，使用Bing, 感谢

**Comment by Linefate** [comment]
请问下，现在是不支持悬停自动翻译注释了吗？
配置了感觉不会生效，只有选中翻译内容后才能翻译
<img width="731" alt="image" src="https://user-images.githubusercontent.com/38858428/189520444-de3d3e28-00a2-4509-9853-0f1ce0353832.png">
配置如下：

<img width="713" alt="image" src="https://user-images.githubusercontent.com/38858428/189520479-889e0475-9f80-4f90-80d7-b0ceacfd5c25.png">

**Comment by intellism** [comment]
> 

支持的，，但是如果有选区(Hover到选区上)，优先翻译选区内容。
