### ISSUE TITLE
rust的文档注释没有去除斜杠

### ISSUE THREAD

**Issue by gelove** [intellism/vscode-comment-translate#129]
<img width="310" alt="image" src="https://user-images.githubusercontent.com/15058512/191299006-ac13a94b-d91f-4ce1-9894-0a8ecfc0f44e.png">

**Comment by gelove** [comment]
这是日志
<img width="281" alt="image" src="https://user-images.githubusercontent.com/15058512/191299518-5921d6bb-1698-4f6d-9a04-122a18085793.png">

**Comment by intellism** [comment]
这是部分语言的textmate语法没有把注释的头标识出来，你可以通过"commentTranslate.ignore"配置，忽略

```json
"commentTranslate.ignore": [

    {
      "languageId": "javascript,typescript,javascriptreact,typescriptreact",
      "regular": "[\\*\\s]+"
    },
    {
      "languageId": "dart",
      "regular": "[\\s|/]+"
    },
    {
      "languageId": "rust",
      "regular": "[\\s|/]+"
    }
  ],
```

**Comment by gelove** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/15058512/191780478-79e08c94-d76a-45dc-bf36-5bd6f392fba2.png">

谢谢，但还是没有合并为一行，我想把末尾的换行改为空格

**Comment by intellism** [comment]
合并翻译需要一个前提是，  本行第一个字母是大写。
当然，需要开启多行合并.
![image](https://user-images.githubusercontent.com/442894/192188782-2d3afdbe-5bf9-419d-93b1-e78f03b95525.png)

**Comment by gelove** [comment]
> 

thx a lot
