### ISSUE TITLE
打开一个单行大文件好像会把vscode卡住

### ISSUE THREAD

**Issue by DCLangX** [intellism/vscode-comment-translate#130]
比如b站的这个打包后的js，本地打开后会导致vscode处于持续阻塞中，cpu占用升高，所有功能都失效
https://s1.hdslb.com/bfs/seed/jinkela/comment-h5/comment-h5.min.js

**Comment by galaxy-s10** [comment]
实锤了，找半天我也找到这插件，一个大文件会导致cpu飙升，并且得重启vscode才行

**Comment by intellism** [comment]
单行文件过长的文件，textmate 进行出来会比较吃内存。  vscode自己是超过20000字符，不处理。。后面会同相同策略。

**Comment by galaxy-s10** [comment]
> 单行文件过长的文件，textmate 进行出来会比较吃内存。 vscode自己是超过20000字符，不处理。。后面会同相同策略。

我觉得这个对于一些调试源码的开发者不太友好，如果开启了悬浮翻译的话，鼠标移到打包好的源码上面就会导致cpu飙升（可能把整个源码当做一个字符串了），需要开启简洁模式之后才能避免鼠标一悬浮就自动翻译，能否加一个配置项，默认最大读取100字符串，但是可以允许修改配置

**Comment by DCLangX** [comment]
> v2.3.0 已修复

厉害，真不戳
