### ISSUE TITLE
[FEAT]增加按钮，将翻译追加到原文末尾而不是直接替换

### ISSUE THREAD

**Issue by YexuanXiao** [intellism/vscode-comment-translate#133]
能否增加按钮，将翻译追加到原文末尾而不是直接替换？

这样方便翻译文档，可以在追加翻译结果之后仍然可以看到原文，方便对翻译进行润色。

**Comment by intellism** [comment]
谢谢反馈，这个可以支持。后面可以加一个配置，是追加还是替换翻译内容。

**Comment by YexuanXiao** [comment]
> 

我说的原文末尾指的翻译原文末尾，不是文件末尾😂

**Comment by jumbojing** [comment]
支持这个增强, 就是增加一个**双语**的选项

**Comment by wangwangxingao** [comment]
能否考虑把翻译的结果设置到剪贴板,然后很方便的ctrl+v了. 
@intellism

**Comment by intellism** [comment]
怎么个交互？
写剪贴板需要非常小心，如果不在使用者预期，可能干扰别人了。

**Comment by wangwangxingao** [comment]
> 怎么个交互？ 写剪贴板需要非常小心，如果不在使用者预期，可能干扰别人了。

目前不是已经有 翻译并替换 的快捷键吗,再添加一个 翻译并保存到剪贴板 的快捷键应该就可以比较方便了
