### ISSUE TITLE
希望可以记住翻译源选择

### ISSUE THREAD

**Issue by ilolita945** [intellism/vscode-comment-translate#136]
默认启动是Google，设置了AliCloud之后，每次都要手动从Google切换至AliCloud，希望开发者能够改进。

**Comment by intellism** [comment]
> 默认启动是Google，设置了AliCloud之后，每次都要手动从Google切换至AliCloud，希望开发者能够改进。

直接设置vscode 用户设置，  通过插件快速设置，是给当前项目设置的，只生效于当前项目。
