### ISSUE TITLE
能否支持语法语义错误提示翻译

### ISSUE THREAD

**Issue by extheor** [intellism/vscode-comment-translate#139]
类似这种
![image](https://user-images.githubusercontent.com/57162041/202995677-15713435-5d9c-4bc9-b4a5-b2bb9752365a.png)

**Comment by intellism** [comment]
这个是能支持的，就是有些细节出来比较麻烦，需要分析翻译片段。目前支持了Hover的内容翻译，但是还是有部分误翻译情况。
![image](https://user-images.githubusercontent.com/442894/203010087-fb1e4b75-8fd7-4d18-a67d-996891be0638.png)
