### ISSUE TITLE
必应、百度翻译 不能用了吗，昨天还可以用的

### ISSUE THREAD

**Issue by jadelxy1997** [intellism/vscode-comment-translate#147]
必应
![image](https://user-images.githubusercontent.com/54530758/212233717-75b3ae64-5263-4a0f-9e2f-b4b82e8a02d3.png)

百度
![image](https://user-images.githubusercontent.com/54530758/212233774-592a1042-8ea3-4e0a-a2d7-3ad53aac67ad.png)

vscode：1.74.3
os：win11

**Comment by intellism** [comment]
我这里，Bing可以使用。Baidu接口升级了，不可以使用了

**Comment by W6STAR** [comment]
我的百度和必应也用不了了
不知道为什么
求大神解决

**Comment by wwwwwen** [comment]
我的也是,一模一样的错误,有什么解决方案吗

**Comment by jadelxy1997** [comment]
用阿里的翻译



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年01月19日 16:35 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [intellism/vscode-comment-translate] 必应、百度翻译 不能用了吗，昨天还可以用的 (Issue #147) |

我的也是,一模一样的错误,有什么解决方案吗

**Comment by lusson-luo** [comment]
谷歌和必应用不了
![image](https://user-images.githubusercontent.com/19859400/217413435-26ece096-1eb3-4bd2-98e9-b00f072bd687.png)
![image](https://user-images.githubusercontent.com/19859400/217413479-5dd0817d-caa2-4884-8000-8c882d26f302.png)
