### ISSUE TITLE
大佬，每个免费源都不能用，求求了😭

### ISSUE THREAD

**Issue by newerliu** [intellism/vscode-comment-translate#163]
[Start translate]: Use 'Google' translate source
[Google]: request error:
 HTTPError: Response code 404 (Not Found) 
 Try again later or change translate source.{"code":"ERR_NON_2XX_3XX_RESPONSE","timings":  ...

[Start translate]: Use 'Bing' translate source
[Bing]: request error:
 Error: Something went wrong! The response is {"statusCode":205,"errorMessage":""}. 

[Start translate]: Use 'DarkCWK.youdao-youdao' translate source --> 这个文案少的可以用，多了就一直正在加载

**Comment by intellism** [comment]
申请下收费服务源，免费的量基本够用，服务更稳定。

**Comment by newerliu** [comment]
感谢大佬😎

**Comment by EmmettHan** [comment]
> 申请下收费服务源，免费的量基本够用，服务更稳定。

如何申请呢？

**Comment by intellism** [comment]
Bing已修复。 google需要科学上网

**Comment by UFO281** [comment]
bing 可以免费用的，反应还很快

**Comment by xiaoli0319** [comment]
> bing 可以免费用的，反应还很快

现在不行

**Comment by intellism** [comment]
> > bing 可以免费用的，反应还很快
> 
> 现在不行

试试 [TranSmart插件](https://marketplace.visualstudio.com/items?itemName=naomi233.comment-translate-transmart)

还可以用其他申请key的也备用下。 https://github.com/intellism/vscode-comment-translate/wiki/%E7%BF%BB%E8%AF%91%E6%9C%8D%E5%8A%A1

**Comment by StoneYss** [comment]
谷歌国内会被墙免费版还有限流, 让AI帮你把翻译原改成bing 或者TranSmart
