### ISSUE TITLE
Bug: 开启插件导致vscode出现双弹窗的情况

### ISSUE THREAD

**Issue by Siykt** [intellism/vscode-comment-translate#173]
Version: v2.3.0

![image](https://github.com/intellism/vscode-comment-translate/assets/44022526/8a97c1b8-7fb8-4af9-9c79-af9f4f6a1f12)

**Comment by intellism** [comment]
是的。目的是为了翻译Hover里面的英语，目前没有识别中文和英语，统统重复出现了。  你可以找一个英文文档试试，效果不错。后面考虑加一层区分，非英文的代码文档不显示。  

当然，如果你不希望翻译Hover内容页可以通过配置关闭。 `commentTranslate.hover.content`
