### ISSUE TITLE
Add option to select source language

### ISSUE THREAD

**Issue by vkhobor** [intellism/vscode-comment-translate#174]
I would like to set the source language not just the target language. Is this possible?

I am looking at a German file that I would like to translate to English.
The problem is these cases 
- Fall(german)-> Fall, Correct would be: Case
- Bild(geman)-> Bild, Correct would be: Picture

Auto -> English translation thinks these are already english words.

If there would be a setting for input language it would be nice.

**Comment by intellism** [comment]
Sure, it's possible. We will add a new configuration option for this in the near future.

**Comment by intellism** [comment]
The configuration option you requested has been added in version 2.3.1.   `commentTranslate.sourceLanguage`

**Comment by vkhobor** [comment]
Thank you
