### ISSUE TITLE
如何只展示 翻译后的提示, 隐藏系统自带的提示呢? 或者....

### ISSUE THREAD

**Issue by each1026** [intellism/vscode-comment-translate#175]
### 问题一
**隐藏英文提示**

![隐藏英文提示](https://cdn.jsdelivr.net/gh/each1026/ImageSave@master/image-2023-07-12-EsUQAy.png)

---

### 问题二
**还有如何设置拓展再不能翻译时不展示提示呢?**

![如何设置拓展再不能翻译时不展示提示呢](https://cdn.jsdelivr.net/gh/each1026/ImageSave@master/image-2023-07-12-cVT7Yg.png)

**Comment by intellism** [comment]
问题一： 目前没办法隐藏原始英文。  vscode api目前不允许插件干扰其他插件的提示内容。 
问题二：已计划修复。如果没有翻译内容，直接忽略翻译提示。

**Comment by each1026** [comment]
> 问题一： 目前没办法隐藏原始英文。 vscode api目前不允许插件干扰其他插件的提示内容。 问题二：已计划修复。如果没有翻译内容，直接忽略翻译提示。

那我可以主动去设置去隐藏这个提示吗 , 只使用翻译自带的提示.  
`问题二：已计划修复。如果没有翻译内容，直接忽略翻译提示。`  但这个功能就要加个开关了

**Comment by intellism** [comment]
问题一： 如果一直都比希望展示翻译内容，可以使用配置关闭  `commentTranslate.hover.content`。 如果临时关闭，可以直接在状态栏快捷关闭
![image](https://github.com/intellism/vscode-comment-translate/assets/442894/163071f6-8c93-46a4-a6bf-ccb54868b420)
问题二：v2.3.1 做了部分优化。没有翻译的内容，默认不再展示，对阅读干扰小了许多。欢迎试用。

**Comment by Alan3344** [comment]
目前来说这个插件是能够很好的在`VSCode`中使用代替`Jetbrins`家族里面那个翻译文档的插件，如果问题一能够解决，真的就很完美了!
已经使用了很久了，支持下

**Comment by intellism** [comment]
> 目前来说这个插件是能够很好的在`VSCode`中使用代替`Jetbrins`家族里面那个翻译文档的插件，如果问题一能够解决，真的就很完美了! 已经使用了很久了，支持下

谢谢支持
