### ISSUE TITLE
翻译悬浮窗内容时，vs code 将悬浮窗内容中的字符转义为字符实体，导致翻译结果包含字符实体。

### ISSUE THREAD

**Issue by hwf1324** [intellism/vscode-comment-translate#176]
在翻译悬浮窗内容时，翻译的结果里经常出现类似 `&nbsp;`、`&quot;` 这样的字符实体代码，查看 Comment Translate 的输出发现，原文中的符号就已经被替换掉了。

这样做的原因也许是 vs code 显示时的需要，但这个转换应该在翻译后进行。

我不清楚该如何解决 vs code 带来的问题，希望有方法可以解决。

**Comment by hwf1324** [comment]
我又尝试了一下，此问题似乎是由 vs code 本身导致的，目前只发现在翻译悬浮窗内容时有此问题。

![image](https://github.com/intellism/vscode-comment-translate/assets/43466291/cd8b32cc-3952-4766-b2f5-0e9a6d758a20)

![image](https://github.com/intellism/vscode-comment-translate/assets/43466291/e47b386f-f16c-4cfd-a2e3-bff0e7affb67)

![image](https://github.com/intellism/vscode-comment-translate/assets/43466291/c81ad503-adad-4864-a9dc-d5c1f0d7ce6e)

**Comment by intellism** [comment]
懂了，方便提供下复现的文件内容吗?

另外再尝试下不同翻译引擎的结果?

**Comment by hwf1324** [comment]
> 懂了，方便提供下复现的文件内容吗?

如果是截图内的文件的话：

https://github.com/nvaccess/nvda/blob/7edac844c303a12305806bb9e011564cad9f2e01/source/inputCore.py#L196

> 另外再尝试下不同翻译引擎的结果?

谷歌的比较聪明，会转换，但是从输出看，传递的时候还是字符实体代码。

![image](https://github.com/intellism/vscode-comment-translate/assets/43466291/ae3bdc1e-eb2d-429e-9600-b3c3e027251d)

**Comment by intellism** [comment]
依赖翻译服务。  output里面是被转义了，实际发出的不是。
