### ISSUE TITLE
提示 command 'commentTranslate.replaceSelections' not found

### ISSUE THREAD

**Issue by fengzhifeng** [intellism/vscode-comment-translate#177]
遇到的问题： 翻译时提示 command 'commentTranslate.replaceSelections' not found
复现流程如图
![2023-07-19 21 45 24](https://github.com/intellism/vscode-comment-translate/assets/25578351/27fe25ca-1978-41b1-a8a8-29bd41e5dc8c)
复现版本: v2.3.1

**Comment by intellism** [comment]
我这里是可以的，不能复现，麻烦提供下输出的日志
![image](https://github.com/intellism/vscode-comment-translate/assets/442894/78b347ae-5874-48d3-b34c-81523e96db73)

**Comment by fengzhifeng** [comment]
<img width="811" alt="image" src="https://github.com/intellism/vscode-comment-translate/assets/25578351/caad846a-3ac1-4f3e-82ac-c7f59578231f">
输出的选项里没有看得到插件的选项，在底部的状态栏中也没有展示插件的选项。
看插件的状态是已经安装完成了。

**Comment by intellism** [comment]
应该是插件没有启动成功。 你重新启动vscode看看

**Comment by fengzhifeng** [comment]
是因为要访问 /用户/.config/configstore/google-translate-api.json ，但是 configstore 文件夹没有权限导致的。
设置权限后可以正常访问了。
