### ISSUE TITLE
翻译语言选择

### ISSUE THREAD

**Issue by zxc177950** [intellism/vscode-comment-translate#178]
配置翻译语言时可以双向配置吗,就是当前字符串为英文，翻译成中文。当前字符串为中文，就翻译成中文。
![image](https://github.com/intellism/vscode-comment-translate/assets/74418202/805faf61-4bcd-47c0-a4df-10af4f1d3595)
目前设置里只支持自动选择来源语言，目标语言只支持一种。

**Comment by zxc177950** [comment]
主要想支持中英互译

**Comment by intellism** [comment]
如果支持互译，需要提前判断当前待翻译内容的语言类型(需要网络请求)，然后再调整到翻译目标语言，这样等待翻译时间会更长，体验不是特别好。 后面考虑下在中文环境下离线判断下。

**Comment by zxc177950** [comment]
好的
