### ISSUE TITLE
请问目标语言设置为中文后，依旧翻译成英文，是设置的问题吗？

### ISSUE THREAD

**Issue by ryuushihou** [intellism/vscode-comment-translate#179]
<img width="1050" alt="截屏2023-07-23 11 41 11" src="https://github.com/intellism/vscode-comment-translate/assets/113272024/4c8dcaa3-4a15-4c46-995e-a6413cfb0b9b">
<img width="939" alt="截屏2023-07-23 11 40 23" src="https://github.com/intellism/vscode-comment-translate/assets/113272024/7ef3a65d-b9cb-47ba-8cfd-e641c22c9f2d">

**Comment by Alan3344** [comment]
你好，我这里没有这个问题

建议你把你代码中的那一串注释贴出来，别人可以看看有没有翻译结果

**Comment by intellism** [comment]
check下工作区配置。  配置有用户配置和工作区配置。。工作区配置会优先用户配置。
![image](https://github.com/intellism/vscode-comment-translate/assets/442894/d321f4f3-464e-40a2-8deb-a384a2d544a3)

**Comment by ryuushihou** [comment]
@intellism @Alan3344  原因找到了  我本地vscode是英文  所以这个插件是英文翻译为英文了  我把vscode调成中文后 就好了。 但是。。。我是想用英文的 有其他的解决方案吗
<img width="699" alt="截屏2023-09-20 0 16 40" src="https://github.com/intellism/vscode-comment-translate/assets/113272024/f7e2bb4c-5e52-4f26-b355-83e5b9c495c5">
