### ISSUE TITLE
测试了下mirror的功能其实是没有实现的，需要修改依赖的包

### ISSUE THREAD

**Issue by x2009again** [intellism/vscode-comment-translate#183]
修改@vitalets/google-translate-token包，增加mirror参数处理，在updateTKK方法中增加mirror判断处理
同时在修改GoogleTranslate.ts中的_translate方法，将mirror传给GoogleToken，这样就可以完全不依赖translate.google.com了，不然就算配置了mirror还是需要设置代理

**Comment by intellism** [comment]
https://github.com/intellism/vscode-comment-translate/pull/146 

这个是社区同学贡献的，它代理的是免费版本。

**Comment by fisherzrj** [comment]
确实是这样，主要是依赖包vitalets/google-translate-token中获取免费token的URL写死如下：
```
got('https://translate.google.' + opts.tld)
```
应该可以复制过来修改一下

**Comment by x2009again** [comment]
> 确实是这样，主要是依赖包vitalets/google-translate-token中获取免费token的URL写死如下：
> 
> ```
> got('https://translate.google.' + opts.tld)
> ```
> 
> 应该可以复制过来修改一下

是的，我都已经说了修改方法了，我自己已经修改好了，也做好了安装包，使用后没有问题了。

**Comment by intellism** [comment]
> > 确实是这样，主要是依赖包vitalets/google-translate-token中获取免费token的URL写死如下：
> > ```
> > got('https://translate.google.' + opts.tld)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 应该可以复制过来修改一下
> 
> 是的，我都已经说了修改方法了，我自己已经修改好了，也做好了安装包，使用后没有问题了。

辛苦提个PR下修复下这个问题。  近期比较忙，没时间处理

**Comment by x2009again** [comment]
大概明天我会发起PR。

**Comment by intellism** [comment]
感谢 @x2009again 修复，已经合并发布到v2.3.2中

#184
