### ISSUE TITLE
能否简单的做下检测，检测部分文字而不做翻译

### ISSUE THREAD

**Issue by Alan3344** [intellism/vscode-comment-translate#185]
像是一般的英文名字函数，判断下选的字词是全字母或者是全中文，不做翻译处理
- ### en -> en
![image](https://github.com/intellism/vscode-comment-translate/assets/60773912/91a38501-043a-47b3-8d48-c6aca4961142)

- ### zh-CN -> zh-CN
![image](https://github.com/intellism/vscode-comment-translate/assets/60773912/180c3f73-e1c2-4824-83e2-cfd81d192619)

**Comment by intellism** [comment]
收到

**Comment by Alan3344** [comment]
不知道是否支持正则匹配选项，这样会更加通用，比如 Markdown 格式
```
# title
[`Auth.Code`](auth/code)
```
等等

**Comment by intellism** [comment]
v3.0.0 部分优化了， 文本内的内容很难完全识别，部分翻译服务处理的比较好。  如腾讯的transSmart
