### ISSUE TITLE
Google translate response  code 429 

### ISSUE THREAD

**Issue by liuyanhang2004** [intellism/vscode-comment-translate#190]
[Start translate]: Use 'Google' translate source
[Google]: request error:
 HTTPError: Response code 429 (Too Many Requests) 
 Try again later or change translate source.{"code":"ERR_NON_2XX_3XX_RESPONSE","timings":{"start":1697686878646,"socket":1697686878651,"lookup":1697686878651,"connect":1697686878651,"secureConnect":1697686878925,"upload":1697686878925,"response":1697686879053,"end":1697686879054,"phases":{"wait":5,"dns":0,"tcp":0,"tls":274,"request":0,"firstByte":128,"download":1,"total":408}},"name":"HTTPError","options":{"agent":{},"decompress":true,"timeout":{"request":10000},"prefixUrl":"","ignoreInvalidCookies":false,"context":{},"hooks":{"init":[],"beforeRequest":[],"beforeError":[],"beforeRedirect":[],"beforeRetry":[],"afterResponse":[]},"followRedirect":true,"maxRedirects":10,"throwHttpErrors":true,"username":"","password":"","http2":false,"allowGetBody":false,"headers":{"user-agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36","accept":"application/json","accept-encoding":"gzip, deflate, br"},"methodRewriting":false,"retry":{"limit":2,"methods":["GET","PUT","HEAD","DELETE","OPTIONS","TRACE"],"statusCodes":[408,413,429,500,502,503,504,521,522,524],"errorCodes":["ETIMEDOUT","ECONNRESET","EADDRINUSE","ECONNREFUSED","EPIPE","ENOTFOUND","ENETUNREACH","EAI_AGAIN"],"backoffLimit":null,"noise":100},"method":"GET","cacheOptions":{},"https":{},"resolveBodyOnly":false,"isStream":false,"responseType":"text","url":"https://www.google.com/sorry/index?continue=https://translate.google.com/translate_a/single%3Fclient%3Dgtx%26sl%3Dauto%26tl%3Dzh-CN%26hl%3Dzh-CN%26dt%3Dat%26dt%3Dbd%26dt%3Dex%26dt%3Dld%26dt%3Dmd%26dt%3Dqca%26dt%3Drw%26dt%3Drm%26dt%3Dss%26dt%3Dt%26ie%3DUTF-8%26oe%3DUTF-8%26otf%3D1%26ssel%3D0%26tsel%3D0%26kc%3D7%26q%3DTitle%2520task%2520name%26tk%3D224672.224672&hl=zh-CN&q=EgRweDalGNnKwqkGIjAEYj2MOZboe5ho_gibM0HXih6g04mMkONFkctgT4IYG7S06WAXgyI008H9zGi63toyAXJaAUM","pagination":{"countLimit":null,"backoff":0,"requestLimit":10000,"stackAllItems":false},"setHost":true}}

**Comment by intellism** [comment]
#2
