### ISSUE TITLE
请问作者大大如何关闭对单词的翻译

### ISSUE THREAD

**Issue by black23eep** [intellism/vscode-comment-translate#192]
![Snipaste_2023-10-31_21-55-21](https://github.com/intellism/vscode-comment-translate/assets/121802039/a4842de4-83b7-4a4d-86c2-3a74443da384)
就是我画圈的的地方

**Comment by intellism** [comment]
第一行是我们插件输出的，单词这部分不是的。check下其他插件。

**Comment by black23eep** [comment]
好的老哥
