### ISSUE TITLE
google 开了梯子为何还是不能用

### ISSUE THREAD

**Issue by tl123987** [intellism/vscode-comment-translate#193]
![图片](https://github.com/intellism/vscode-comment-translate/assets/65206700/c66b698f-63c7-46f0-b369-359b59a3e14c)

**Comment by intellism** [comment]
![image](https://github.com/intellism/vscode-comment-translate/assets/442894/b03016cb-3ec4-4a3f-b8db-e1a66391550e)
我这里只是有些慢，反应是正常的。。看日志你那边404了，可能再check下网络

**Comment by intellism** [comment]
![image](https://github.com/intellism/vscode-comment-translate/assets/442894/a1b094f5-ea18-405a-95b4-a2ae6ea01c0d)
你配置有问题，，不要使用CN，CN已经下线了，配置会COM 
![image](https://github.com/intellism/vscode-comment-translate/assets/442894/35398faf-cb49-4e8c-bd1e-8f8fb65ba50c)

**Comment by tl123987** [comment]
为啥挂梯子网页很快，这个反应就好慢

**Comment by intellism** [comment]
> 为啥挂梯子网页很快，这个反应就好慢

这个我需要排查下，应该是获取token的服务地址有问题。
