### ISSUE TITLE
2.3.3版本双击选中文字出现翻译框后，聚焦点自动到了弹出的翻译框，导致无法按下任何打字键，只能ESC取消后，键盘才能输入

### ISSUE THREAD

**Issue by akatong** [intellism/vscode-comment-translate#197]
如标题

**Comment by intellism** [comment]
v2.3.3已经做了修复，但是需要依赖 vscode 1.86版本生效
#196

**Comment by lifetin** [comment]
我也一样的. 折腾我一天了好受不了.啊

**Comment by lifetin** [comment]
配置失效, 把自动翻译关掉也不行.
设置为要按ctrl键才翻.也是不行

**Comment by akatong** [comment]
> 我也一样的. 折腾我一天了好受不了.啊

可以回退插件版本到老的版本就行

**Comment by lifetin** [comment]
vs刚升了, 最新也是1.85,不能到1.86 ,只能降级了

**Comment by intellism** [comment]
> > 我也一样的. 折腾我一天了好受不了.啊
> 
> 可以回退插件版本到老的版本就行

你是退回到哪个版本可以？  应该是非常老的版本才行吧?

**Comment by akatong** [comment]
> > > 我也一样的. 折腾我一天了好受不了.啊
> > 
> > 
> > 可以回退插件版本到老的版本就行
> 
> 你是退回到哪个版本可以？ 应该是非常老的版本才行吧?

2.3.2的插件版本

**Comment by intellism** [comment]
> > > > 我也一样的. 折腾我一天了好受不了.啊
> > > 
> > > 
> > > 可以回退插件版本到老的版本就行
> > 
> > 
> > 你是退回到哪个版本可以？ 应该是非常老的版本才行吧?
> 
> 2.3.2的插件版本

2.3.2不行的吧，2.3.3就是为了解这个bug。

**Comment by akatong** [comment]
> > > > > 我也一样的. 折腾我一天了好受不了.啊
> > > > 
> > > > 
> > > > 可以回退插件版本到老的版本就行
> > > 
> > > 
> > > 你是退回到哪个版本可以？ 应该是非常老的版本才行吧?
> > 
> > 
> > 2.3.2的插件版本
> 
> 2.3.2不行的吧，2.3.3就是为了解这个bug。

我目前一切正常，就是他自动升级插件到了2.3.3才出现了这个问题，我回退到2.3.2就没问题了

**Comment by heartacker** [comment]
> v2.3.3已经做了修复，但是需要依赖 vscode 1.86版本生效 #196

也就是说，需要 内测版本的vscode 才支持对吧，

![image](https://github.com/intellism/vscode-comment-translate/assets/1876302/6a2f1069-d3df-45f1-a1fa-3175c8729839)

**Comment by ChnTamap** [comment]
我也是遇到这个问题好久了，才找到是这个插件的问题
![vscode_c_test](https://github.com/intellism/vscode-comment-translate/assets/36532501/5aef3075-02a6-4f81-a141-0817d79e5fb5)
![vscode_py_test](https://github.com/intellism/vscode-comment-translate/assets/36532501/4c4b2077-7e89-4167-8a0f-b212ebceb2e2)

**Comment by ccsFW** [comment]
所以现在只能更新vscode来解决嘛

**Comment by heartacker** [comment]
@所有人 请更新 @VSCode
