### ISSUE TITLE
替换时删掉了原来的空格

### ISSUE THREAD

**Issue by 791314247** [intellism/vscode-comment-translate#199]
我的理解是替换时可能用了正则表达式取消/*等符号，但是请不要去除空格，否则格式就乱了

**Comment by DKozachenko** [comment]
I encountered the same problem.

In addition, a few examples:
![2024-07-02 19-01-59](https://github.com/intellism/vscode-comment-translate/assets/56767227/f376c14d-4278-4fcf-9bcd-ee3b04d771e2)

![2024-07-02 19-00-51](https://github.com/intellism/vscode-comment-translate/assets/56767227/e21a6638-70d3-4a3c-94b8-6e4c7ee91c83)

![2024-07-02 19-01-35](https://github.com/intellism/vscode-comment-translate/assets/56767227/0194ddcc-9503-4ed6-ae82-742882499cce)

**Comment by intellism** [comment]
v3.0.0已做优化
