### ISSUE TITLE
Google翻译接口拒绝服务

### ISSUE THREAD

**Issue by intellism** [intellism/vscode-comment-translate#2]
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"><meta name="viewport" content="initial-scale=1"><title>https://translate.google.com/translate_a/single?client=gtx&amp;dt=t&amp;dj=1&amp;ie=UTF-8&amp;sl=auto&amp;tl=zh-CN&amp;q=%2F%2F%20Does%20the%20client%20support%20the%20%60workspace%2Fconfiguration%60%20request%3F%0A%2F%2F%20If%20not%2C%20we%20will%20fall%20back%20using%20global%20settings</title></head>
<body style="font-family: arial, sans-serif; background-color: #fff; color: #000; padding:20px; font-size:18px;" onload="e=document.getElementById('captcha');if(e){e.focus();}">
<div style="max-width:400px;">
<hr noshade size="1" style="color:#ccc; background-color:#ccc;"><br>
<div style="font-size:13px;">
Our systems have detected unusual traffic from your computer network.  Please try your request again later.  <a href="#" onclick="document.getElementById('infoDiv0').style.display='block';">Why did this happen?</a><br><br>
<div id="infoDiv0" style="display:none; background-color:#eee; padding:10px; margin:0 0 15px 0; line-height:1.4em;">
This page appears when Google automatically detects requests coming from your computer network which appear to be in violation of the <a href="//www.google.com/policies/terms/">Terms of Service</a>. The block will expire shortly after those requests stop.<br><br>This traffic may have been sent by malicious software, a browser plug-in, or a script that sends automated requests.  If you share your network connection, ask your administrator for help &mdash; a different computer using the same IP address may be responsible.  <a href="//support.google.com/websearch/answer/86640">Learn more</a><br><br>Sometimes you may see this page if you are using advanced terms that robots are known to use, or sending requests very quickly.
</div><br>

IP address: 205.204.117.29<br>Time: 2018-10-26T08:32:12Z<br>URL: https://translate.google.com/translate_a/single?client=gtx&amp;dt=t&amp;dj=1&amp;ie=UTF-8&amp;sl=auto&amp;tl=zh-CN&amp;q=%2F%2F%20Does%20the%20client%20support%20the%20%60workspace%2Fconfiguration%60%20request%3F%0A%2F%2F%20If%20not%2C%20we%20will%20fall%20back%20using%20global%20settings<br>
</div>
</div>
</body>
</html>

**Comment by intellism** [comment]
我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？


IP 地址：205.204.117.29
时间：2018-10-26T08:32:47Z
网址：https://translate.google.com/translate_a/single?client=gtx&dt=t&dj=1&ie=UTF-8&sl=auto&tl=zh-CN&q=%2F%2F%20Does%20the%20client%20support%20the%20%60workspace%2Fconfiguration%60%20request%3F%0A%2F%2F%20If%20not%2C%20we%20will%20fall%20back%20using%20global%20settings

**Comment by waiaan** [comment]
> 我们的系统检测到您的计算机网络中存在异常流量。请稍后重新发送请求。为什么会这样？
> 
> IP 地址：205.204.117.29
> 时间：2018-10-26T08:32:47Z
> 网址：https://translate.google.com/translate_a/single?client=gtx&dt=t&dj=1&ie=UTF-8&sl=auto&tl=zh-CN&q=%2F%2F%20Does%20the%20client%20support%20the%20%60workspace%2Fconfiguration%60%20request%3F%0A%2F%2F%20If%20not%2C%20we%20will%20fall%20back%20using%20global%20settings

用代理都会这样

**Comment by intellism** [comment]
添加google translate token
