### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Highter87** [intellism/vscode-comment-translate#20]
You can implement a setting that, when enabled, will translate if the Ctrl key is pressed

**Comment by intellism** [comment]
Good idea. I try to implement.

**Comment by intellism** [comment]
@Highter87 v1.4.2
![image](https://user-images.githubusercontent.com/442894/68593956-8092c600-04d1-11ea-985b-55166387f386.png)

**Comment by Highter87** [comment]
Fine! thank you friend
