### ISSUE TITLE
阿里云翻译

### ISSUE THREAD

**Issue by qq451147668** [intellism/vscode-comment-translate#207]
阿里云翻译  翻译服务源设置成什么呢  AliYun?Alicloud?  
![image](https://github.com/intellism/vscode-comment-translate/assets/59364429/f49a8d55-8456-48be-bb84-84aa1eca87a8)

**Comment by intellism** [comment]
![image](https://github.com/intellism/vscode-comment-translate/assets/442894/7166d205-c823-41bf-96b5-b73842198b9a)
翻译源切换配置，通过命令吧。
