### ISSUE TITLE
extension.js  中发送网络请求 ， 会重定向到127.0.0.1:8080

### ISSUE THREAD

**Issue by dh360** [intellism/vscode-comment-translate#21]
你好， 我现在在学习你的项目， 并且尝试自己做一个插件，自己使用， 
但是我现在在extension.js 中 使用 `axios`或者 `request` 发送一个网络请求，都会被重定义到 
`127.0.0.1:8080`
```
node     10.15.3
vsCode   1.36.1
macOS    10.14.5
```

`extension.js` In this file,  I  make a network request:
```
axios.get(`https://www.google.com`)
.then((rep) => {
 vscode.window.showInformationMessage('something');
});
```
and  get a  follow   error:
![image](https://user-images.githubusercontent.com/7079487/61383235-d8813d80-a8e0-11e9-9e7c-fe0f462b0060.png)
in fact ,  no matter what URL i visit,  it will all point to  `127.0.0.1:8080`

**Comment by intellism** [comment]
检查下是否使用了代理吧。
