### ISSUE TITLE
双击选中变量后,弹出的提示会吞掉我的光标

### ISSUE THREAD

**Issue by 3269573270** [intellism/vscode-comment-translate#212]
当我双击选中一个变量的时候，光标消失，会导致我没有办法删除这个变量。
我开启和关闭了3次这个插件，我认为是有一点点问题的，会让我感觉很不流畅。
如果很忙就算了。。 感谢开源 感谢插件

**Comment by intellism** [comment]
你的vscode版本是多少, v1.86.0以上应该修复了。  #197

**Comment by 3269573270** [comment]
我的 VScode 版本是1.87.2 
![微信图片_20240325095358](https://github.com/intellism/vscode-comment-translate/assets/49808806/73c2f77c-5160-460f-8bcb-972104a15f69)
但是结果还是一样，我有一段录像 

https://github.com/intellism/vscode-comment-translate/assets/49808806/633f9c49-10eb-48b1-9073-790dcd10dc7f

**Comment by intellism** [comment]
v3.0.0 已修复
