### ISSUE TITLE
有办法隐藏自带的提示吗? 或者手动设置隐藏?

### ISSUE THREAD

**Issue by eachann1024** [intellism/vscode-comment-translate#216]
![Image_2024-05-31_11-40-53](https://github.com/intellism/vscode-comment-translate/assets/43348055/e67857a3-5b02-49ec-a14c-daa01b189b0c)

**Comment by intellism** [comment]
目前还没办法。 vscode不允许插件去干预其他插件的hover信息提示

**Comment by eachann1024** [comment]
> 目前还没办法。 vscode不允许插件去干预其他插件的hover信息提示

1. 那怎么隐藏原有的提示 还能显示翻译呢
2. 有个问题, 中文的注释也会给我翻译一次

**Comment by eachann1024** [comment]
> 目前还没办法。 vscode不允许插件去干预其他插件的hover信息提示

还在吗

**Comment by intellism** [comment]
> > 目前还没办法。 vscode不允许插件去干预其他插件的hover信息提示
> 
> 1. 那怎么隐藏原有的提示 还能显示翻译呢
> 2. 有个问题, 中文的注释也会给我翻译一次

1. 不能隐藏原有提示，vscode没有提供隐藏口子。
2. 这个是bug，没有做语言探测，默认都显示出来了，可以优化。
