### ISSUE TITLE
翻译整个文件, 内容一多就无反应了

### ISSUE THREAD

**Issue by eachann1024** [intellism/vscode-comment-translate#217]
!!!!! 很需要这个功能呀, 目测15000行之后就不行了

![image](https://github.com/intellism/vscode-comment-translate/assets/43348055/d30c9480-3b0a-4487-93bc-e35ccac56a9f)

**Comment by intellism** [comment]
单行超过20000字符的不处理，但是行应该没限制。

上传下原始文件，调试下。

**Comment by eachann1024** [comment]
> 单行超过20000字符的不处理，但是行应该没限制。
> 
> 上传下原始文件，调试下。

> 没有时间解释了

[index.d.zip](https://github.com/user-attachments/files/15605330/index.d.zip)
