### ISSUE TITLE
有的提示不会被翻译

### ISSUE THREAD

**Issue by eachann1024** [intellism/vscode-comment-translate#218]
![image](https://github.com/intellism/vscode-comment-translate/assets/43348055/b4856486-fddf-40ff-840b-22586f3a0064)

[仓库来源
](https://github.com/antfu/eslint-config)

**Comment by intellism** [comment]
识别是纯代码提示的时候，不会翻译。。这个场景看，好像是bug

**Comment by eachann1024** [comment]
> 识别是纯代码提示的时候，不会翻译。。这个场景看，好像是bug

这bug 还挺别致

**Comment by intellism** [comment]
v3.0.0 已支持错误提醒翻译
