### ISSUE TITLE
中文的提示也会翻译一次

### ISSUE THREAD

**Issue by eachann1024** [intellism/vscode-comment-translate#219]
是因为有url , 识别成英文才翻译了吗?

![image](https://github.com/intellism/vscode-comment-translate/assets/43348055/3fa399e1-2159-4a8f-852b-d37cd6ad5654)

**Comment by intellism** [comment]
默认无脑翻译，不管语言的。

**Comment by intellism** [comment]
v3.0.0 尽可能判断原文语言，不翻译中文。
