### ISSUE TITLE
选中的文字无法删除

### ISSUE THREAD

**Issue by zb134614** [intellism/vscode-comment-translate#222]
双击选中的文字触发了翻译 ， 无法删除这个文字

**Comment by intellism** [comment]
没有复现，请提供更多信息。

**Comment by longlongvip** [comment]
> 没有复现，请提供更多信息。

选择文字，打算修改文字，但是触发了翻译，此时就无法修改文字了

**Comment by longlongvip** [comment]
> > 没有复现，请提供更多信息。
> 
> 选择文字，打算修改文字，但是触发了翻译，此时就无法修改文字了，注VSCode 信息

![image](https://github.com/user-attachments/assets/362a31c4-0751-494b-95c9-0e206427e61e)

**Comment by longlongvip** [comment]
> > 没有复现，请提供更多信息。
> 
> 选择文字，打算修改文字，但是触发了翻译，此时就无法修改文字了

![image](https://github.com/user-attachments/assets/5cc6f63b-faef-410c-bbf7-c933cea724d2)

**Comment by intellism** [comment]
#212 #197

**Comment by intellism** [comment]
这个问题修复过的
禁用其他插件看看，是不是其他hover引起的失焦。

**Comment by UnicornZhang** [comment]
同样的问题，卸载插件正常
<img width="260" alt="image" src="https://github.com/user-attachments/assets/9828dc88-0756-467c-8fc7-ae74d0a6b564">

**Comment by UnicornZhang** [comment]
补充，未开启任何功能
<img width="456" alt="image" src="https://github.com/user-attachments/assets/7f41de2e-7a9a-4683-b386-f360d7a7b276">
选中文本，会失去光标焦点，无法输入或删除，卸载插件后正常

**Comment by intellism** [comment]
感谢反馈，麻烦提供这个入口提交下问题，提供更多信息。

![image](https://github.com/user-attachments/assets/ae981f45-df15-4e12-b0b7-f12abcc270b5)
![image](https://github.com/user-attachments/assets/05a33d90-3423-417c-8cbd-0d4f9f94062b)

**Comment by intellism** [comment]
v3.0.0 已修复
