### ISSUE TITLE
能否调用 TONGYI Lingma 插件的对话功能用于翻译?

### ISSUE THREAD

**Issue by Antecer** [intellism/vscode-comment-translate#226]
最近经常使用 通义灵码 插件的对话功能来翻译代码注释,我发现它的翻译比通用翻译引擎更精准,而且速度很快.
虽然它的插件描述是用于智能生成代码,但这并不妨碍它成为vscode的专用翻译官(●'◡'●)

大家都是vscode的插件,于是有没有可能直接访问 通义灵码 的聊天对话接口取得翻译结果呢?

**Comment by intellism** [comment]
需要通义灵码开放接口才可以，他插件也是需要登录认证的
