### ISSUE TITLE
常常会把不需要翻译的 / 本来就是中文的内容翻译了

### ISSUE THREAD

**Issue by eachann1024** [intellism/vscode-comment-translate#227]
![Image_2024-07-11_13-55-23](https://github.com/intellism/vscode-comment-translate/assets/43348055/08e11551-896f-40e1-a099-c36be6d5ebba)

**Comment by intellism** [comment]
这个Hover片段里面有英文片段，为了结构完整，都翻译了，尽量做了原有功能保留。

**Comment by intellism** [comment]
v3.0.0,做了语言判断，尽量准确翻译。
