### ISSUE TITLE
Idea support plz!

### ISSUE THREAD

**Issue by lijinshanmx** [intellism/vscode-comment-translate#23]
Idea support plz!

**Comment by intellism** [comment]
ctrl 后再显示？

**Comment by lijinshanmx** [comment]
鼠标移动上去自动翻译能做到吗？就跟vscode一样

**Comment by intellism** [comment]
现在就是自动翻译的呀?

**Comment by lijinshanmx** [comment]
是吗？我装错插件了？我再去看看

**Comment by intellism** [comment]
https://marketplace.visualstudio.com/items?itemName=intellsmi.comment-translate

**Comment by lijinshanmx** [comment]
我说的是intellij idea，不是vscode，就是能新支持idea吗？

**Comment by lijinshanmx** [comment]
<img width="381" alt="截屏2019-10-0913 51 51" src="https://user-images.githubusercontent.com/6552340/66454976-028b6b80-ea9c-11e9-8a67-fe8131b86365.png">

**Comment by lijinshanmx** [comment]
这个好像不是de

**Comment by intellism** [comment]
intellij idea支持不了，没开发过idea的插件。
