### ISSUE TITLE
在开启Format On Type 设置后，发现与 Mintlify doc writer 插件存在冲突

### ISSUE THREAD

**Issue by ezhengping** [intellism/vscode-comment-translate#233]
该冲突主要影响按键使用。

在同时安装该插件和Mintlify doc writer插件和操作设置Format On Type 开启的情况下
在选中文本内容时出现无法输入任何按键情况。
<img width="966" alt="Snipaste_2024-08-22_11-10-18" src="https://github.com/user-attachments/assets/1d1d8dd2-ac10-424d-8dcb-23c142a223f5">
<img width="1909" alt="Snipaste_2024-08-22_11-11-14" src="https://github.com/user-attachments/assets/ed34d9a3-3c28-435e-b718-35935c752741">

**Comment by intellism** [comment]
v3.0.0 已修复
