### ISSUE TITLE
选中文字鼠标失去焦点，无法进行键盘操作

### ISSUE THREAD

**Issue by UnicornZhang** [intellism/vscode-comment-translate#235]
Type: <b>Bug</b>

描述在此，https://github.com/intellism/vscode-comment-translate/issues/222，还有最新版本号是多少，我看你用的3.0.0.，我这边最高2.3.3

Extension version: 2.3.3
VS Code version: Code 1.92.2 (Universal) (fee1edb8d6d72a0ddff41e5f71a671c23ed924b9, 2024-08-14T17:29:30.058Z)
OS version: Darwin arm64 23.6.0
Modes:

**Comment by intellism** [comment]
收到，感谢反馈。设备与我相同，但是我这边没有复现。   应该还是划词翻译触发hover引起的，下个版本增加一个配置项。

**Comment by Sean10** [comment]
同样遇到该问题, disable hover后就正常. 即便设置了concise默认不触发翻译, 但只要触发hover就会无法键盘操作输入删除

**Comment by intellism** [comment]
v3.0.0 已修复
