### ISSUE TITLE
在copilot chat 中遮挡注释

### ISSUE THREAD

**Issue by swttkonjjj** [intellism/vscode-comment-translate#236]
![image](https://github.com/user-attachments/assets/94e44aa7-7a8c-48be-8b11-53aec41413cc)

**Comment by intellism** [comment]
你是默认开启了 “沉浸式”翻译了吗？  在chat框中，添加空白行会失效，所以会与原文内容重叠了。

**Comment by swttkonjjj** [comment]
> 你是默认开启了 “沉浸式”翻译了吗？ 在chat框中，添加空白行会失效，所以会与原文内容重叠了。
怎么关闭 “沉浸式”翻译，在设置中没有找到开关

**Comment by swttkonjjj** [comment]
![image](https://github.com/user-attachments/assets/819bb24e-a7c1-485b-a2cd-583e62f75f87)
![image](https://github.com/user-attachments/assets/af642758-0f90-4121-a31e-0805a2e13669)

**Comment by intellism** [comment]
> > 你是默认开启了 “沉浸式”翻译了吗？ 在chat框中，添加空白行会失效，所以会与原文内容重叠了。
> > 怎么关闭 “沉浸式”翻译，在设置中没有找到开关
`commentTranslate.browse.enabled` 默认就是关闭的，文档右上角可打开当前文档。
![image](https://github.com/user-attachments/assets/282f1dd7-18d1-4287-8177-a11e9280d580)

---
这是个bug 我看如何屏蔽掉chat内的翻译吧。

**Comment by swttkonjjj** [comment]
在插件更新后就这样了，折腾半天找不到这个设置，重启下vscode就有了。

**Comment by intellism** [comment]
我用了一段时间沉浸式，喜欢使用'占位'模式，现在习惯把自己的注释也翻译成英文了。
