### ISSUE TITLE
为什么这个预览翻译把我注释翻译了, 甚至还是中文转英文   , 离了个大谱 

### ISSUE THREAD

**Issue by Super1Windcloud** [intellism/vscode-comment-translate#239]

**Comment by intellism** [comment]
什么意思？

**Comment by Super1Windcloud** [comment]
可以把功能改为自动翻译函数名而不是翻译注释

**Comment by intellism** [comment]
函数名的信息很少，hover看一次就知道了。 注释默认不是自动翻译的，是不是你设置了。

另外中文英文互译，是许多人反馈添加的，这里可以加个配置，自由选择

**Comment by macouen** [comment]
+1 注释为啥会自动翻译，没找到对应的开关

**Comment by macouen** [comment]
<img width="554" alt="image" src="https://github.com/user-attachments/assets/c90e7b06-8940-4252-a351-226f10c59e1c">

**Comment by intellism** [comment]
![image](https://github.com/user-attachments/assets/2039afdb-6228-48aa-8a12-fc0361140dbb)
这个配置是控制是否开启的，设置了默认false,手动配置，或者单文档又上角打开。  已经有人反馈了，不知道是不是第一次安装的时候配置会自动生效。
