### ISSUE TITLE
Message: Request textDocument/hover failed with message: Cannot find module 'oniguruma'

### ISSUE THREAD

**Issue by hellojqk** [intellism/vscode-comment-translate#29]
版本: 1.41.0-insider
提交: 27cd33d891eb23e370b672e751be9fe8b3748ac1
日期: 2019-11-08T19:11:22.061Z
Electron: 6.1.4
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.0.0

[Error - 9:26:13 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot find module 'oniguruma'
Require stack:
- /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/node_modules.asar/vscode-textmate/release/main.js
- /Users/wangyang/.vscode-insiders/extensions/intellsmi.comment-translate-1.4.1/server/out/util/patch-asar-require.js
- /Users/wangyang/.vscode-insiders/extensions/intellsmi.comment-translate-1.4.1/server/out/syntax/TextMateService.js
- /Users/wangyang/.vscode-insiders/extensions/intellsmi.comment-translate-1.4.1/server/out/Comment.js
- /Users/wangyang/.vscode-insiders/extensions/intellsmi.comment-translate-1.4.1/server/out/server.js
- /Users/wangyang/.vscode-insiders/extensions/intellsmi.comment-translate-1.4.1/client/node_modules/vscode-languageclient/lib/utils/electronForkStart.js
  Code: -32603 

新装的vscode和插件,mac上和win10上的稳定版和开发板 都报这个错，不知道算是vs问题还是插件问题

**Comment by intellism** [comment]
#30 相同。  vscode 1.40 兼容问题。 textmate有升级。合并处理
