### ISSUE TITLE
报错,无法使用

### ISSUE THREAD

**Issue by BestLovelyGod** [intellism/vscode-comment-translate#3]
[Error - 下午1:43:10] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'map' of undefined
  Code: -32603

**Comment by Alisusu** [comment]
I have the same question!

**Comment by a1liz** [comment]
the same question!

**Comment by intellism** [comment]
> [Error - 下午1:43:10] Request textDocument/hover failed.
> Message: Request textDocument/hover failed with message: Cannot read property 'map' of undefined
> Code: -32603

已修复
