### ISSUE TITLE
鼠标放在注释上，不支持预览了，我知道出现了什么问题

### ISSUE THREAD

**Issue by 1309232313** [intellism/vscode-comment-translate#30]
鼠标放在注释上，不支持预览了，我知道出现了什么问题

**Comment by hellojqk** [comment]
跟我提的是一个问题，输出里边选择 Comment Translate就看到了

**Comment by 1309232313** [comment]
您可以说的明白一点么，我没找到怎么设置，新手实在是找不到

 

发件人: lol <notifications@github.com> 
发送时间: 2019年11月11日 10:00
收件人: intellism/vscode-comment-translate <vscode-comment-translate@noreply.github.com>
抄送: 1309232313 <1309232313@qq.com>; Author <author@noreply.github.com>
主题: Re: [intellism/vscode-comment-translate] 鼠标放在注释上，不支持预览了，我知道出现了什么问题 (#30)

 

跟我提的是一个问题，输出里边选择 Comment Translate就看到了

**Comment by hellojqk** [comment]
ctrl+j 打开面板，选择面板第二栏输出，右侧有个下拉框，选择Comment Translate可以看到错误日志，目前还没有解决办法，[稳定版1.39.2目前可用](https://code.visualstudio.com/updates/v1_39)，新版本和开发板最新的都有问题

**Comment by intellism** [comment]
vscode version 1.40.0,兼容问题。

**Comment by intellism** [comment]
原因已定位, vscode-textmate 4.3.0移除对 oniguruma 的直接依赖。 需要使用wasm兼容处理

**Comment by intellism** [comment]
@1309232313 @hellojqk v1.4.2已修复

**Comment by hellojqk** [comment]
> @ 1309232313 @hellojqk v1.4.2已修复

可以用了，谢谢

**Comment by 1309232313** [comment]
好的，谢谢

**Comment by xiaoosi** [comment]
你好，在v1.42.1版本上又出现了这个问题
```
[Error - 上午12:13:05] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot find module 'oniguruma'
Require stack:
- c:\Users\asus\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar\vscode-textmate\release\main.js
- c:\Users\asus\.vscode\extensions\xuedao.super-translate-1.0.9\server\out\util\patch-asar-require.js
- c:\Users\asus\.vscode\extensions\xuedao.super-translate-1.0.9\server\out\syntax\TextMateService.js
- c:\Users\asus\.vscode\extensions\xuedao.super-translate-1.0.9\server\out\Comment.js
- c:\Users\asus\.vscode\extensions\xuedao.super-translate-1.0.9\server\out\server.js
- c:\Users\asus\.vscode\extensions\xuedao.super-translate-1.0.9\client\node_modules\vscode-languageclient\lib\utils\electronForkStart.js
  Code: -32603 
```
在查看go语言源码库时不支持代码和注释预览了
