### ISSUE TITLE
希望能够支持双语言互译

### ISSUE THREAD

**Issue by MxDany** [intellism/vscode-comment-translate#31]
希望可以把翻译功能改为双语言互译

**Comment by intellism** [comment]
请描述下场景，和使用方式。

**Comment by MxDany** [comment]
> 请描述下场景，和使用方式。

选择两个互译语言，例如中文<->英文
1. 当注释为中文时，翻译成英文。
2. 当注释为英文时，翻译成中文。
这样，就不用去状态栏切换语言了。

**Comment by intellism** [comment]
> > 请描述下场景，和使用方式。
> 
> 选择两个互译语言，例如中文<->英文
> 
> 1. 当注释为中文时，翻译成英文。
> 2. 当注释为英文时，翻译成中文。
>    这样，就不用去状态栏切换语言了。

 如果使用这种模式，还需要多一次判断当前语言，目前使用的google免费接口，在内网场景很容易被封掉，后面再看看是否支持。谢谢反馈。

**Comment by mmmmmmmgo** [comment]
将 `commentTranslate.targetLanguage`配置 强制写成 `auto`
