### ISSUE TITLE
远程模式(SSH和WSL)下，翻译C代码有问题

### ISSUE THREAD

**Issue by MxDany** [intellism/vscode-comment-translate#32]
当VSCODE工作在远程模式下时，C代码不能翻译

**Comment by MxDany** [comment]
![image](https://user-images.githubusercontent.com/20413031/69595459-8bee0180-103a-11ea-96af-07c8740dcd00.png)

**Comment by MxDany** [comment]
![image](https://user-images.githubusercontent.com/20413031/69595479-99a38700-103a-11ea-9492-268ef1599bff.png)

**Comment by TonyZhouTuo** [comment]
我也遇到了一样问题，在SSH模式下，注释可以通过替换的方式显示，output窗口也有注释信息出来，但无法弹出。本地的vscode环境可以正常弹出窗口

**Comment by intellism** [comment]
> 我也遇到了一样问题，在SSH模式下，注释可以通过替换的方式显示，output窗口也有注释信息出来，但无法弹出。本地的vscode环境可以正常弹出窗口

应该是Hover消息有丢失，还没有复现环境。

**Comment by djfly** [comment]
我也遇到在wsl ubuntu(windows Linux子系统)下无法使用，弹出加载，然后就没然后了，在win下正常
这个插件很不错啊，体验非常好，可惜在wsl里面用不了，@intellism 怎么打开调试开关， 我看看可以修复不

**Comment by cool-delete** [comment]
+1 默认安装在wsl里面的 打开vscode后 wsl-remote to ubuntu无法使用 不弹窗 不使用wsl-remote到目标位置直 非调试模式下可以翻译 但是调试模式就不行了..
![image](https://user-images.githubusercontent.com/13638610/86993726-510a9980-c1d7-11ea-8b8a-4889eba38e62.png)
![image](https://user-images.githubusercontent.com/13638610/86993799-87481900-c1d7-11ea-83bb-39bb9ca562a6.png)
@intellism

**Comment by cool-delete** [comment]
>  默认安装在wsl里面的
> 
安装在win侧才有弹窗 但是这样很分割wsl-remote的使用体验

**Comment by bigtruck** [comment]
我也有这个问题，现在有解决方法了吗？

**Comment by zbz-cool** [comment]
同问+, 不只是C代码有问题, 其他场景都无法正常工作

**Comment by pavlelee** [comment]
remote ssh not work, output is empty.
![image](https://user-images.githubusercontent.com/5382358/91376888-c64a3080-e850-11ea-88dd-e5b54688c989.png)

**Comment by intellism** [comment]
> 我也遇到在wsl ubuntu(windows Linux子系统)下无法使用，弹出加载，然后就没然后了，在win下正常
> 这个插件很不错啊，体验非常好，可惜在wsl里面用不了，@intellism 怎么打开调试开关， 我看看可以修复不

这边没有 windows环境以及linux子系统的环境。 你fork下，调试看看

**Comment by cgoder** [comment]
> > 我也遇到在wsl ubuntu(windows Linux子系统)下无法使用，弹出加载，然后就没然后了，在win下正常
> > 这个插件很不错啊，体验非常好，可惜在wsl里面用不了，@intellism 怎么打开调试开关， 我看看可以修复不
> 
> 这边没有 windows环境以及linux子系统的环境。 你fork下，调试看看

的确在WSL环境下无法正常使用。-

**Comment by shjyh** [comment]
wsl java/groovy/gradle 可以正常显示，其它语言都显示不出来

**Comment by wyfhust** [comment]
是的，我也发现同样问题，wsl环境下，bib可以正常翻译，但是markdown不行

**Comment by dalaomai** [comment]
win下遠程模式到centos，懸浮翻譯不可用

**Comment by pompeyY** [comment]
window上 wsl里面还是不能用 本地是可以用的 这个问题现在有解决方案吗 平常开发 一般用的都是wsl

**Comment by Hareis** [comment]
插件是不是被放弃了 有人修改这个bug吗？

**Comment by intellism** [comment]
#58 合并
