### ISSUE TITLE
合并多行注释时，超过2行的注释翻译格式有问题

### ISSUE THREAD

**Issue by drrrMikado** [intellism/vscode-comment-translate#33]
翻译两行注释时：
![image](https://user-images.githubusercontent.com/11224565/71455728-540ce200-27d1-11ea-8e75-ef4f0fee5320.png)
翻译超过两行注释时：
![image](https://user-images.githubusercontent.com/11224565/71455764-83235380-27d1-11ea-8481-eb4a06c6fccf.png)

另外有单独的`// ` 能否作为每块注释的分隔符。像go的官方源码中，有大量这样的注释出现：
![image](https://user-images.githubusercontent.com/11224565/71455815-b8c83c80-27d1-11ea-9485-c675c1ca82a4.png)

图中代码示例：https://github.com/golang/go/blob/master/src/context/context.go

**Comment by intellism** [comment]
#### 合并多行注释 （源语言只支持英语）
![Multi-line-merge](./doc/image/multi-line-merge.gif)

**Comment by drrrMikado** [comment]
> #### 合并多行注释 （源语言只支持英语）
> ![Multi-line-merge](https://github.com/intellism/vscode-comment-translate/raw/master/doc/image/multi-line-merge.gif)

已经开启multiLineMerge了，两行时翻译显示正常

**Comment by drrrMikado** [comment]
设置问题，有个workspace的setting，好像就没用到user的setting，把workspace的setting.json删了就行了。

**Comment by drrrMikado** [comment]
![image](https://user-images.githubusercontent.com/11224565/71497862-fd68dc00-2894-11ea-9ea7-81a9c97a5555.png)
这个只翻译了一行

**Comment by intellism** [comment]
> ![image](https://user-images.githubusercontent.com/11224565/71497862-fd68dc00-2894-11ea-9ea7-81a9c97a5555.png)
> 这个只翻译了一行

提供下样例代码，和语言

**Comment by drrrMikado** [comment]
> > ![image](https://user-images.githubusercontent.com/11224565/71497862-fd68dc00-2894-11ea-9ea7-81a9c97a5555.png)
> > 这个只翻译了一行
> 
> 提供下样例代码，和语言

https://github.com/golang/go/blob/master/src/context/context.go#L106
```golang
// If Done is not yet closed, Err returns nil.
// If Done is closed, Err returns a non-nil error explaining why:
// Canceled if the context was canceled
// or DeadlineExceeded if the context's deadline passed.
// After Err returns a non-nil error, successive calls to Err return the same error.
Err() error
```

**Comment by onnezezt** [comment]
建议行注释只翻译一行，块级注释合并。
部分语言块级注释如ts语言在翻译时候携带注释符合导致断句翻译结果会有很大差异。
```ts
/**
 * The client code works with an instance of a concrete creator, albeit through
 * its base interface. As long as the client keeps working with the creator via
 * the base interface, you can pass it any creator's subclass.
 */
```
```
/ **
  *客户端代码使用具体创建者的实例，尽管通过
  *它的基本接口。 只要客户通过与创作者保持合作
  *基本接口，您可以将其传递给任何创建者的子类。
  * /
```
去掉注释符就会好很多
```
The client code works with an instance of a concrete creator, albeit 
through its base interface. As long as the client keeps working with 
the creator via the base interface, you can pass it any creator's 
subclass.

客户端代码虽然通过其基本接口与具体创建者的实例一起工作。 只要
客户端继续通过基本接口与创建者合作，就可以将其传递给任何创建者
的子类。
```

**Comment by qsazx874** [comment]
关于合并多行注释，如果能获取到文件类型，可以根据文件类型进行处理。或者在设置里手动设置文件类型，只能固定某种语言进行翻译。
希望作者留个支持方式，我想稍稍支持一下。

**Comment by intellism** [comment]
> 建议行注释只翻译一行，块级注释合并。
> 部分语言块级注释如ts语言在翻译时候携带注释符合导致断句翻译结果会有很大差异。
> 
> ```ts
> /**
>  * The client code works with an instance of a concrete creator, albeit through
>  * its base interface. As long as the client keeps working with the creator via
>  * the base interface, you can pass it any creator's subclass.
>  */
> ```
> 
> ```
> / **
>   *客户端代码使用具体创建者的实例，尽管通过
>   *它的基本接口。 只要客户通过与创作者保持合作
>   *基本接口，您可以将其传递给任何创建者的子类。
>   * /
> ```
> 
> 去掉注释符就会好很多
> 
> ```
> The client code works with an instance of a concrete creator, albeit 
> through its base interface. As long as the client keeps working with 
> the creator via the base interface, you can pass it any creator's 
> subclass.
> 
> 客户端代码虽然通过其基本接口与具体创建者的实例一起工作。 只要
> 客户端继续通过基本接口与创建者合作，就可以将其传递给任何创建者
> 的子类。
> ```

好建议。后面考虑支持

**Comment by intellism** [comment]
> 关于合并多行注释，如果能获取到文件类型，可以根据文件类型进行处理。或者在设置里手动设置文件类型，只能固定某种语言进行翻译。
> 希望作者留个支持方式，我想稍稍支持一下。

不是特别明白，怎么处理

**Comment by qsazx874** [comment]
> > 关于合并多行注释，如果能获取到文件类型，可以根据文件类型进行处理。或者在设置里手动设置文件类型，只能固定某种语言进行翻译。
> > 希望作者留个支持方式，我想稍稍支持一下。
> 
> 不是特别明白，怎么处理

C/C++/Java语言使用 //和/**/格式，Python 使用#和"，因此如果能获取到当前文件后缀，就能判断是那种语言，进而根据语法规则对注释删除头部和尾部，进行正确的多行合并。

**Comment by intellism** [comment]
v2.0.0 已优化
