### ISSUE TITLE
希望能加入有道和百度翻译的切换功能。

### ISSUE THREAD

**Issue by QiuShiqi** [intellism/vscode-comment-translate#35]
现在经常出现不可用的情况，希望能加入有道和百度翻译的切换功能。

[Google Translate]: request error
 "Too Many Requests" 
 Try again in 5 minutes.

**Comment by BreezeStark** [comment]
![不能翻译](http://img.golang.space/PicGo/1586484094068-sJ6TN0.png)

不能翻译  ,  赞同楼上

**Comment by SusuDOS** [comment]
有时候，翻译结果不是那么好.
[url=https://sm.ms/image/No4v5Cn3tkwjalL][img]https://i.loli.net/2020/06/14/No4v5Cn3tkwjalL.jpg[/img][/url]

**Comment by intellism** [comment]
v1.5.0 已新增 Bing、Baidu翻译源

https://github.com/intellism/vscode-comment-translate/blob/master/CHANGELOG.md#150-2021-8-2
