### ISSUE TITLE
怎么将代码中的注释翻译为指定语言

### ISSUE THREAD

**Issue by zhangdexian** [intellism/vscode-comment-translate#40]

**Comment by intellism** [comment]
https://github.com/intellism/vscode-comment-translate/blob/master/doc/image/cn/status-bar.gif

**Comment by zhangdexian** [comment]
我的意思是说扫描项目下的所有注释并翻译。。

**Comment by zhangdexian** [comment]
你好，增加了一个按照glob模式扫描所有的文件并自动翻译和替换注释的功能，能不能加下提交代码的权限？
