### ISSUE TITLE
无法显示选中文字翻译结果（）

### ISSUE THREAD

**Issue by cn-adger** [intellism/vscode-comment-translate#41]
![微信截图_20200927193517](https://user-images.githubusercontent.com/45423611/94363974-a2506800-00f8-11eb-8578-b0c4e9ebff72.png)

**Comment by cn-adger** [comment]
f墙也显示不出结果......vscode也信任授权了

**Comment by intellism** [comment]
![image](https://user-images.githubusercontent.com/442894/94509256-688d7780-0246-11eb-9207-fa6f25df7d1e.png)
看看控制台信息提示。

**Comment by cn-adger** [comment]
> ![image](https://user-images.githubusercontent.com/442894/94509256-688d7780-0246-11eb-9207-fa6f25df7d1e.png)
> 看看控制台信息提示。
没有任何输出。目前遇到问题：1.有的单词无法翻译（批量翻译或悬停翻译都不成功）2.翻译大量词汇之后会出现有一定的时间段内无法执行任何翻译操作(完全失效 选中的字替换只会闪红色)
墙&不墙都试过，应该跟这个没关系。
![t](https://user-images.githubusercontent.com/45423611/94651270-c72c2180-032a-11eb-9693-bbe230c861b7.gif)

**Comment by TinaSprunt** [comment]
> > ![图像](https://user-images.githubusercontent.com/442894/94509256-688d7780-0246-11eb-9207-fa6f25df7d1e.png)
> > 当前遇到
> > 问题：1.大量翻译词汇之后会出现有时间段内无法执行。任何的翻译操作（完全失效了，选墙的字原地球红色）
> > &不都试过，应该跟这个墙一样。
> > ![吨](https://user-images.githubusercontent.com/45423611/94651270-c72c2180-032a-11eb-9693-bbe230c861b7.gif)

这个问题有什么解决办法吗？我也出现了这个问题

**Comment by TinaSprunt** [comment]
我也出现了这个问题，用了一段时间之后，突然无法使用
![image](https://user-images.githubusercontent.com/38268966/125752590-72b1a3a7-de49-4d88-b325-bdb536bd23bc.png)

**Comment by intellism** [comment]
v1.5.0 已新增 Bing、Baidu翻译源

https://github.com/intellism/vscode-comment-translate/blob/master/CHANGELOG.md#150-2021-8-2
