### ISSUE TITLE
 Include PT-BR support

### ISSUE THREAD

**Issue by edsonrbispo** [intellism/vscode-comment-translate#43]
Include PT-BR support, and if it is possible to translate Errors Lens, and documentation when hovering over the method.
Success

![image](https://user-images.githubusercontent.com/16540088/98692209-9db0dd80-234d-11eb-8933-c8f59d8b30e6.png)

**Comment by intellism** [comment]
Errors Lens is can't translate in VSCODE.  Add PT-BR is simple。

**Comment by edsonrbispo** [comment]
Got it ... Congratulations on the extension!
