### ISSUE TITLE
it can not work well recently? what happened?

### ISSUE THREAD

**Issue by hackftz** [intellism/vscode-comment-translate#46]

**Comment by intellism** [comment]
Please give more information.

**Comment by hackftz** [comment]
![image](https://user-images.githubusercontent.com/33424860/106987655-eb03e600-67a8-11eb-81f4-348b686779a6.png)

hello the chinese words means it's loading now...
but no translated words show up

I am in china.

For suggestion, in my country,Baidu is the most used search engine just like google in USA or another country, could this plugin can add the baidu translate registry?

[baidu translate](https://fanyi.baidu.com/)

you can click it and try it on, thks!

**Comment by intellism** [comment]
I got it. Support in the next version.

**Comment by hackftz** [comment]
> I got it. Support in the next version.

bingo! It will be very useful to many developers!

**Comment by hackftz** [comment]
> I got it. Support in the next version.

bingo! It will be very useful to many developers!
