### ISSUE TITLE
想把地址换成translate.google.com

### ISSUE THREAD

**Issue by hanjinfeng0309** [intellism/vscode-comment-translate#47]
想把地址换成translate.google.com而不是translate.google.cn，设置里没有这个配置，我应该怎么做到呢？重新编译整个插件？

**Comment by intellism** [comment]
translate.google.cn不可以访问吗，还是说你的地区比较慢？

**Comment by hanjinfeng0309** [comment]
我平时开发在公司内网环境下都是挂着代理，导致我translate.google.cn无法访问，translate.google.com反而可以。

![image](https://user-images.githubusercontent.com/63445267/109477521-167da600-7ab3-11eb-9aea-85668be1120d.png)

![image](https://user-images.githubusercontent.com/63445267/109477588-28f7df80-7ab3-11eb-8555-6ec79fe138eb.png)

如果能添加一个配置项那就最好了。

**Comment by intellism** [comment]
收到。

**Comment by hanjinfeng0309** [comment]
感谢作者大大

**Comment by jianboy** [comment]
可以把 translate.google.cn 地址抽离成一个用户设置:

```
   "commentTranslate.translateUrl": "translate.google.cn",
```

注意：国内很多时候也不能访问 translate.google.cn 这个网站，有些时候网站返回**404**。。

![image](https://user-images.githubusercontent.com/11532015/130398109-b9348d4f-f2e7-4c7a-b0df-03e2f3c078a9.png)

question：

是否可以增加 bing.com 翻译？

```
"commentTranslate.translateUrl": "www.bing.com/translator",
```

**Comment by heartacker** [comment]
建议设置添加一个选项
```json
"commentTranslate.source": [
"Bing",
"Google.com",
"Google.cn",
"Baidu"
]
```

**Comment by intellism** [comment]
v2.0.0 已支持. 设置方法稍有差异，请查看配置项
