### ISSUE TITLE
目前，擴展名不翻譯任何內容。

### ISSUE THREAD

**Issue by xabru** [intellism/vscode-comment-translate#48]
也許這是Google API和限制的問題。
如何放置自定義api或實現繞過？

**Comment by intellism** [comment]
请提供更多信息。 
![image](https://user-images.githubusercontent.com/442894/109619262-86ebfc00-7b73-11eb-8fb2-6d02a9110117.png)

**Comment by xabru** [comment]
嗨，看來問題已經解決，目前工作正常。
