### ISSUE TITLE
[Google Translate]: request error  "Too Many Requests"   Try again in 5 minutes.

### ISSUE THREAD

**Issue by xabru** [intellism/vscode-comment-translate#49]
Output console Extension:
[Google Translate]: request error
 "Too Many Requests" 
 Try again in 5 minutes.

is there any way to implement the external google api?

**Comment by lifetin** [comment]
我也遇到了,让我重试, 什么内容都不显示.建议老大增加一个独立的自己的APIKEY来配置,防止共享的key有拦截或并发限制

**Comment by intellism** [comment]
v1.5.0 已新增 Bing、Baidu翻译源

https://github.com/intellism/vscode-comment-translate/blob/master/CHANGELOG.md#150-2021-8-2
