### ISSUE TITLE
翻译结果支持多个

### ISSUE THREAD

**Issue by nshusr** [intellism/vscode-comment-translate#50]
![image](https://user-images.githubusercontent.com/45023042/112450681-997edd00-8d8f-11eb-8a1c-46a98afbebe6.png)
![image](https://user-images.githubusercontent.com/45023042/112450718-a00d5480-8d8f-11eb-9ad3-ede03f509203.png)

**Comment by intellism** [comment]
console里面可以考虑提升更多重点单词语义
