### ISSUE TITLE
二次开发

### ISSUE THREAD

**Issue by jiaqiwang969** [intellism/vscode-comment-translate#55]
国外发展了很多有价值的c++类库，这些类库大多都有非常丰富的学习文档，而且是和代码本身紧密相连的。对于国内的学习者而言，不乏有些吃力。希望在开源方面，也能出一份力。

比如最近在翻译一个有限元的类库，代码中不乏会嵌入很多注释，这块手动翻译非常棘手，我想到办法用正则提取翻译，https://github.com/jiaqiwang969/deal.II-translator。无意间发现你用vscode的一个实现，更是深受启发！

我想在您代码的基础上实现二次开发，目前您的功能可以选中然后翻译替代。
但是，还没办法满足批量精确翻译的能力，需要增加两个功能：
1. 比如打开一个文件，可以批量(全部)的自动选中所有的 comment，i.e "/**  ...  */"，然后实现替换。
2. "/**  ...  */" 注释中的内容，不乏会存在一些 特殊字段和符号，比如“@file”， 这些是不需要google 翻译替换的。因此，需要增加正则筛选的功能，去除这些特殊的字块后，再进行翻译替换。

这是我目前的初次尝试遇到的问题：
尝试clone你的代码进行调试F5，但是一直出错，查阅后仍没办法解决（只好搁置了），光一开始的调试过程就进行不下去了。
F5调试错误：
Activating extension 'intellsmi.comment-translate' failed: Cannot find module '/Users/wjq_1/Downloads/vscode-comment-translate/client/out/extension' Require stack: - /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js - /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js.

**Comment by intellism** [comment]
你应该没有 安装好依赖。  需要进入  client  和 server文件夹安装   npm install
具体你可以看看 vscode插件开发文档。   
https://code.visualstudio.com/api/get-started/your-first-extension

**Comment by intellism** [comment]
为了支持不同语言的注释提取，使用了vscode高亮代码的 vscode-textmate。  你也可以参考下。  单一语言的化，正则方案也是不错的选择。

**Comment by jiaqiwang969** [comment]
感谢你的回复。
我尝试进入到cd client，对其进行库安装“npm install”，或是“npm run update-vscode”。
会显示如下错误：
不知道有何对策？
 
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'update-vscode' ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'preupdate-vscode', 'update-vscode', 'postupdate-vscode' ]
5 info lifecycle comment-translate-client@0.0.1~preupdate-vscode: comment-translate-client@0.0.1
6 info lifecycle comment-translate-client@0.0.1~update-vscode: comment-translate-client@0.0.1
7 verbose lifecycle comment-translate-client@0.0.1~update-vscode: unsafe-perm in lifecycle true
8 verbose lifecycle comment-translate-client@0.0.1~update-vscode: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/wjq_1/Downloads/vscode-comment-translate/client/node_modules/.bin:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/texlive/2020/bin/x86_64-darwin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/ff++/mpich3/bin:/Applications/VMware Fusion.app/Contents/Public:/Library/TeX/texbin:/Library/Apple/usr/bin:/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin:/usr/local/opt/gnu-getopt/bin:/usr/local/texlive/2020/bin/x86_64-darwin:/opt/anaconda3/bin:/opt/anaconda3/condabin:/Library/Frameworks/Python.framework/Versions/3.9/bin
9 verbose lifecycle comment-translate-client@0.0.1~update-vscode: CWD: /Users/wjq_1/Downloads/vscode-comment-translate/client
10 silly lifecycle comment-translate-client@0.0.1~update-vscode: Args: [ '-c', 'vscode-install' ]
11 silly lifecycle comment-translate-client@0.0.1~update-vscode: Returned: code: 1  signal: null
12 info lifecycle comment-translate-client@0.0.1~update-vscode: Failed to exec update-vscode script
13 verbose stack Error: comment-translate-client@0.0.1 update-vscode: `vscode-install`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid comment-translate-client@0.0.1
15 verbose cwd /Users/wjq_1/Downloads/vscode-comment-translate/client
16 verbose Darwin 20.4.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "update-vscode"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error comment-translate-client@0.0.1 update-vscode: `vscode-install`
22 error Exit status 1
23 error Failed at the comment-translate-client@0.0.1 update-vscode script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
