### ISSUE TITLE
希望可以交互式的翻译，然后以驼峰式的格式返回结果

### ISSUE THREAD

**Issue by mogeko** [intellism/vscode-comment-translate#56]
在想变量名、函数名时很有用。

至于怎么交互，我的想法是：

`Ctrl + Shift + P` -> 选择`交互式的翻译` -> 输入要翻译的内容 -> 返回结果

望采纳。

**Comment by intellism** [comment]
这个之前有考虑过。。可能可以做一个新插件。。  named  ，  而且不是简单翻译，可能需要判断位置，是类名、方法名、变量名等，使用不同的翻译和推荐规则。。  

目前这个插件还是解决阅读的问题为主。

**Comment by intellism** [comment]
v3.0.0 已简单实现，欢迎试用反馈
