### ISSUE TITLE
[Google Translate]: request error

### ISSUE THREAD

**Issue by YinBuLiao** [intellism/vscode-comment-translate#59]
![image](https://user-images.githubusercontent.com/35324248/125601157-92ae86c1-5d10-4892-8d3d-929ed236c5be.png)
没翻译几次就请求失败了

**Comment by intellism** [comment]
v1.5.0 已新增 Bing、Baidu翻译源

https://github.com/intellism/vscode-comment-translate/blob/master/CHANGELOG.md#150-2021-8-2
