### ISSUE TITLE
google翻译接口返回空

### ISSUE THREAD

**Issue by intellism** [intellism/vscode-comment-translate#6]
当前token翻译方法实现，需要重找方法。

**Comment by intellism** [comment]
仅仅是临时服务不可用，已恢复

**Comment by intellism** [comment]
内网用户访问过多了，才被google限制。 应该IP限制的

**Comment by intellism** [comment]
gtx也被玩儿坏，必须上自行配置appkey的方法

**Comment by YLQZ** [comment]
这个翻译确实挺好使，但是有一个bug就是在连续翻译多次之后，谷歌翻译为空，这是啥bug

**Comment by intellism** [comment]
> 这个翻译确实挺好使，但是有一个bug就是在连续翻译多次之后，谷歌翻译为空，这是啥bug

google api接口限制。 目前看主要出现在局域网（同一出口IP）访问api次数过多引起的。

**Comment by nuochong** [comment]
1. 我也出现了同样的问题：有时可以翻译成功有时失败，能否考虑新增切换百度/有道词典API，本地配置网络。
2. 功能建议在悬停翻译对话框中增加一个“替换”按钮，当用户判断单条翻译有效，点击替换直接替换掉原文内容。

**Comment by intellism** [comment]
> 插件非常棒，但是使用的时候发现了一些问题和需要优化的地方：
> 
> 1. 我也出现了同样的问题：有时可以翻译成功有时失败，能否考虑新增切换百度/有道词典API，本地配置虚拟专用网，减轻内网的压力。
> 2. 功能建议在悬停翻译对话框中增加一个“替换”按钮，当用户判断单条翻译有效后，点击替换直接替换掉原文内容。

1. 后面有计划添加多翻译引擎支持，包括google自己配置api
2. “替换” 是低频操作，可以是选中区域翻译功能。

**Comment by qq1312119064** [comment]
最近在攻读一些源码，非常依赖这个翻译插件，然而这两天一到下午谷歌翻译就没有结果了，过好长时间才好，相当影响效率，望优化，或者提供切换翻译API的功能

**Comment by intellism** [comment]
v1.5.0 已新增 Bing、Baidu翻译源
