### ISSUE TITLE
readme.md文件中能否贴出使用步骤或者快捷键

### ISSUE THREAD

**Issue by TinaSprunt** [intellism/vscode-comment-translate#60]
readme.md文件中能否贴出使用步骤或者快捷键，光有gif图实在看不明白，比如较复杂的：
  - 4. 翻译并替换选择内容
  - 5. 选中最后一次翻译区域命令

**Comment by TinaSprunt** [comment]
# 翻译并替换选择内容使用方式

自力更生摸索了一下，虽然这个问题很沙雕，但是没有使用教程有时候就很悲伤，因为真实使用的vscode配置环境往往不是示例gif中那么一干二净啥也没装

**1.选中翻译段落**
![1](https://user-images.githubusercontent.com/38268966/125737034-fadb3d70-6b11-4c5e-a1a4-3e0471b2108b.png)

**2.按F1唤醒命令面板，选择替换翻译内容（或者设置快捷键）**
这一步readme的gif直接就出现了待选项，但实际上如果你安装了很多插件，那么你会发现根本多到你找不到，所以最好输入一部分关键字配合查找
建议还是选择设置替换翻译内容的快捷键，省得每次都要打开命令面板找
![2](https://user-images.githubusercontent.com/38268966/125737045-d5e2c331-736e-4e6f-8fb9-509a39cfdfb9.png)
![2-1](https://user-images.githubusercontent.com/38268966/125738175-d1823693-9ee5-4719-ad6c-2c241a79b32f.png)

**3.设置好之后直接选中待翻译内容，按下自定义的快捷键即可完成替换**
![3](https://user-images.githubusercontent.com/38268966/125737055-23a54797-861e-45b4-9abb-29ffeea58e4b.png)

**4.最终效果**
总体来说，使用体验感极佳，nice!
![4](https://user-images.githubusercontent.com/38268966/125737059-fe21d232-9fa8-4fef-a5d2-374c84f2137e.png)

# 选中最后一次翻译区域命令使用方式
1. 参上，一样找到配置项，添加快捷键，然后愉快的开始用

**Comment by MollyBa** [comment]
咋安装的这是？ 没看明白

**Comment by 567MEI13** [comment]
![image](https://github.com/intellism/vscode-comment-translate/assets/88084071/3b4b5fbb-90d4-48b0-bea2-f2ae707da025)
zen怎么就到这个comment translate命令行的

**Comment by intellism** [comment]
v3.0.0 已添加
