### ISSUE TITLE
新版本

### ISSUE THREAD

**Issue by bjwanghao** [intellism/vscode-comment-translate#62]
啥时能在更新(新版本)  [谷歌翻译]：请求错误“请求过多”

**Comment by intellism** [comment]
收到。 出现这个问题是同一个IP请求过量被google服务器限制请求。特别是公司场景，有多人使用这个服务的时候，特别容易触发。 近期更新一个版本，增加其他备选翻译渠道。

**Comment by bjwanghao** [comment]
怎么才能解决呢

**Comment by intellism** [comment]
v1.5.0 已新增 Bing、Baidu翻译源

https://github.com/intellism/vscode-comment-translate/blob/master/CHANGELOG.md#150-2021-8-2
