### ISSUE TITLE
快捷键和vscode 默认快捷键冲突问题

### ISSUE THREAD

**Issue by heartacker** [intellism/vscode-comment-translate#63]
新增加的`ctrl+shift+t` 和vscode 默认的快捷键是冲突的。
本人非常不建议，甚至强烈反对任何和默认键冲突的快捷键绑定。因为这样会导致用户的困惑。比如以前是重新打开，结果现在变成了翻译转换。

![image](https://user-images.githubusercontent.com/1876302/127942143-a1b4b987-a4c7-4705-b1d5-0f45da368ecb.png)
1. 建议跟换没有冲突的快捷键
2. 增加 `when` 筛选 [vscode when clause](https://code.visualstudio.com/api/references/when-clause-contexts#conditional-operators),比如选中了文本，同时当前文本是可以编辑非只读的等条件。

**Comment by intellism** [comment]
mac下没有与系统行为快捷键冲突，所以使用了这边。

when条件是比较好的建议，后面发布更新小版本修复掉。

**Comment by heartacker** [comment]
>  mac下没有与系统行为快捷键冲突，所以使用了这边。
> 
> when条件是比较好的建议，后面发布更新小版本修复掉。

谢谢，建议考虑跨平台快捷键，毕竟vscode是跨平台编辑器。

**Comment by heartacker** [comment]
你好。<kbd>ctrl+shift+t</kbd> 是windows 下的重开标签页的快捷键。此快捷键对windows 平台是比较重要和常用的，类似 MacOS 的<kbd>Cmd+shift+t</kbd>，由于团队中使用这个都收到了影响。请问是否可以快速修复影响。解决这个困惑。
否则windows下无法使用这个快捷键进行重开标签页。建议更换为<kbd>alt+shift+t</kbd> 或者删除在window下的绑定。谢谢啦

**Comment by heartacker** [comment]
建议：
- 所有平台都使用 <kbd>alt+shift+t</kbd>，这样不会造成冲突。
- Windows/Linux 平台使用 <kbd>alt+shift+t</kbd>，MacOS 使用 <kbd>ctrl+shift+t</kbd>，这样能保持你的习惯。

个人倾向于使用前者。希望作者可以快速修复一下。真的非常感谢。

**Comment by wsytlzdh** [comment]
此快捷键确实给 Windows 下的平台造成困扰。
毕竟 ctrl 其实就是 mac 的cmd 键。希望作者可以尽快修复。

**Comment by heartacker** [comment]
你好，此问题可以处理下吗？谢谢

**Comment by intellism** [comment]
> 你好，此问题可以处理下吗？谢谢

添加了when条件。 快捷键都有冲突风险，使用建议自定义规避。

**Comment by heartacker** [comment]
不赞同此观点，因为这个定义的快捷键 影响的不仅仅是我，而是所有的 windows 用户。也许你用的是mac，但是如果你用win电脑。也许你会换一种想法。

还是再次建议考虑一下，

我个人其实很清楚如何解决，是指考虑到所有 windows 用户，我在这边提个建议。

再次感谢
