### ISSUE TITLE
当悬浮在函数/类等关键词上注释不能正确翻译，需要跳转到函数内悬浮在注释上才翻译

### ISSUE THREAD

**Issue by jianboy** [intellism/vscode-comment-translate#65]
![image](https://user-images.githubusercontent.com/11532015/129864724-6f7c99e8-7f51-4685-a72b-f3bf26e59624.png)

**Comment by intellism** [comment]
只能翻译文档内容，包括注释、变量名等。。  其他系统提示类的，翻译不了。

**Comment by jianboy** [comment]
对于 flutter 代码，注释部分没有被翻译哦。

**Comment by intellism** [comment]
> 对于 flutter 代码，注释部分没有被翻译哦。
鼠标移到 代码里的注释 

![image](https://user-images.githubusercontent.com/442894/130069202-bc6327da-5766-4efc-bc13-9705beeb8902.png)

**Comment by jianboy** [comment]
flutter代码，注释是：

**///  三个 斜杠开头**，和java/C++代码注释不同。 举个例子：

```
/// Mathematical constants and functions, plus a random number generator.
///
/// To use this library in your code:
/// ```dart
/// import 'dart:math';
/// ```
/// {@category Core}
library dart.math;

import "dart:_internal" show SystemHash;

part "point.dart";
part "random.dart";
part "rectangle.dart";

/// Base of the natural logarithms.
///
/// Typically written as "e".
const double e = 2.718281828459045;

/// Natural logarithm of 10.
///
/// The natural logarithm of 10 is the number such that `pow(E, LN10) == 10`.
/// This value is not exact, but it is the closest representable double to the
/// exact mathematical value.
const double ln10 = 2.302585092994046;

```

**Comment by intellism** [comment]
识别注释，不是通过正则，是通过vscode textmate，只要安装了高亮插件，应该都可以识别的。
![image](https://user-images.githubusercontent.com/442894/130381931-294d495d-a3f6-4acf-b108-7e4b84d0c0a2.png)

**Comment by jianboy** [comment]
我理解了，鼠标悬浮在注释的地方才可以翻译：
![动画 (9) (1)](https://user-images.githubusercontent.com/11532015/130394982-c20807a7-8977-4c22-a5f7-32dd78f0a647.gif)

**在关键词上悬浮不能正确翻译：**
![动画 (9) (2)](https://user-images.githubusercontent.com/11532015/130395721-2b59984a-ce7d-401b-8feb-60124aecf24a.gif)
