### ISSUE TITLE
[support] 增加临时关闭翻译功能

### ISSUE THREAD

**Issue by jianboy** [intellism/vscode-comment-translate#66]
这是一个建议：

点击状态栏按钮图标：
![image](https://user-images.githubusercontent.com/11532015/130396351-e6f33b8f-3c67-4249-b960-4676ca3ee5b0.png)

弹出选择语言框，在列表最上面添加一项选项：
开启和关闭 -comment-translate 功能，草图如下：
![image](https://user-images.githubusercontent.com/11532015/130396578-81ab1196-68b9-413b-b9e7-132a3da2e20b.png)

类似于 github copilot的开关功能：

关：
![image](https://user-images.githubusercontent.com/11532015/130396390-7b79cd24-5cab-40aa-9bf7-9b676bc1eee1.png)

开：
![image](https://user-images.githubusercontent.com/11532015/130396918-b0273f1b-13da-442c-9cfe-5f399b085ae8.png)

**Comment by intellism** [comment]
v2.0.0已支持。
