### ISSUE TITLE
mac 不翻译了

### ISSUE THREAD

**Issue by yanghuohua** [intellism/vscode-comment-translate#70]
[Comment Translate] Google

Get headquarter list =>

[Comment Translate] Google

Handle selection change =>

有箭头，但是不显示中文翻译了

**Comment by intellism** [comment]
提供下日志信息。 大概率是局域网请求次数过多，被google临时封IP了。可以切换 bing或者baidu翻译源。
![image](https://user-images.githubusercontent.com/442894/133773174-490bda97-bbd3-423c-9779-7660ba82aed3.png)

**Comment by yanghuohua** [comment]
[Google Translate]: request error
 {"code":"ETIMEDOUT","connect":true} 
 Try again in 5 minutes.

我在公司和家里都试了，都不能显示

**Comment by intellism** [comment]
看样子是网络不同。  先切换下翻译源吧。

**Comment by yanghuohua** [comment]
翻译源在哪里切换

**Comment by MoonCheung** [comment]
> 翻译源在哪里切换

在vscode设置上面有，自行搜索

**Comment by yanghuohua** [comment]
> > 翻译源在哪里切换
> 
> 在vscode设置上面有，自行搜索

谢谢兄弟，搞定了

**Comment by zhuziyi1989** [comment]
Google源出了问题。

**Comment by intellism** [comment]
> Google源出了问题。
> 
> ![image](https://user-images.githubusercontent.com/4889586/134801885-5ad152c0-367b-4f89-bea6-c02b2cba8ff0.png)

被墙了

**Comment by zhuziyi1989** [comment]
> > Google源出了问题。
> 
> > 
> 
> > ![image](https://user-images.githubusercontent.com/4889586/134801885-5ad152c0-367b-4f89-bea6-c02b2cba8ff0.png)
> 
> 
> 
> 被墙了.你尝试浏览器访问 https://translate.google.cn/?sl=en&tl=zh-CN&op=translate&hl=zh-CN 

全局代理也都不可以

**Comment by kuangkuangkuangha** [comment]
我的mac也不行，更换翻译源是选区吗

**Comment by kuangkuangkuangha** [comment]
> 翻译源在哪里切换

翻译源在设置->用户->扩展
