### ISSUE TITLE
windows 也不能翻译了 

### ISSUE THREAD

**Issue by Ytired** [intellism/vscode-comment-translate#71]
以为是我电脑的问题，但是今天帮同学下载了过后，试过了也不能翻译

**Comment by intellism** [comment]
看样子是网络不同。  先切换下翻译源吧。

**Comment by Ytired** [comment]
> 先看切换下翻译源吧。

请问一下作者大大 翻译源在哪切换啊

**Comment by intellism** [comment]
插件设置

![image](https://user-images.githubusercontent.com/442894/134268975-b0866ae4-1f75-4f3b-9824-f294483d44c2.png)

**Comment by FateArth** [comment]
一样谷歌翻译不行了，切换成本百度就好了

**Comment by lainbo** [comment]
我也是谷歌不行了，暂时换成百度了

**Comment by Dcx199302** [comment]
这个问题还是存在呀，翻译结果只显示了：[Comment Translate] Google  
建议如果真的没有翻译结果的时候，显示一下网络错误。空白状态看着很懵

**Comment by Dcx199302** [comment]
打开设置的时候看到： 翻译服务源  默认变成了空（昨晚关机前还是正常的），切换google又可以用了。 能不能稍微处理一下

**Comment by marchanbbb** [comment]
确实，翻译源变空了，不翻译，换了google的源就变成loading...

**Comment by intellism** [comment]
> 确实，翻译源变空了，不翻译，换了google的源就变成loading...

翻译源空了？  默认就是空的，代码里兜底google.  不空的时候是不是换了项目，默认读了项目配置

**Comment by intellism** [comment]
> 建议如果真的没有翻译结果的时候，显示一下网络错误。空白状态看着很懵

免费API就存在这个问题，  同一IP调用多了就被限制。   错误的时候没有显示错误信息，还是怕干扰,所以只在控制台输出了。

**Comment by Dcx199302** [comment]
并没有很频繁调用api，我昨天切换了baidu源，目前没有出问题。很好用

**Comment by intellism** [comment]
> 并没有很频繁调用api，我昨天切换了baidu源，目前没有出问题。很好用

是看IP的，局域网有其他同学访问也会算一起。Google很可能被墙了（局部），近期很多同学反馈访问不了，可以尝试下这个链接是否可以直接访问 https://translate.google.cn/?hl=zh-CN&tab=wT#en/zh-CN/

**Comment by Dcx199302** [comment]
我这边应该不是IP频繁访问的问题，建议将源默认设置baidu吧。 并不是所有同学都通过墙在线使用。

**Comment by FateArth** [comment]
![image](https://user-images.githubusercontent.com/70887549/135014787-c304b6d6-d6d8-4578-9dd0-4cb465da38f1.png)
google反正就是不让翻译我谷歌翻译都能正常访问，baidu反正就能用就行了。
![image](https://user-images.githubusercontent.com/70887549/135014972-f14d0c63-2bb5-469d-8493-9c25f843ce7c.png)

**Comment by marchanbbb** [comment]
> > 确实，翻译源变空了，不翻译，换了google的源就变成loading...
> 
> 翻译源空了？ 默认就是空的，代码里兜底google. 不空的时候是不是换了项目，默认读了项目配置
> 
> 方便的化，截图看看。

那应该是默认是空，可以支持修改google的翻译源链接吗。因为平时都有挂着fq工具

**Comment by luojiego** [comment]
我切换成 bing，对百度我还是不太放心
