### ISSUE TITLE
关于使用效果的建议

### ISSUE THREAD

**Issue by ltxhhz** [intellism/vscode-comment-translate#73]
> 插件很好用，非常感谢，有几个建议🙏  
> 希望选择目标语言后
> ![image](https://user-images.githubusercontent.com/51697596/139854745-e04ea93d-c1c4-41da-a5d7-982a3c59bd92.png)

1. 有混合语言的内容能依然翻译成目标语言
![image](https://user-images.githubusercontent.com/51697596/139854498-d3a1730d-e2a9-43d1-9566-3e9d3d9ba177.png)

2. 选择内容翻译能直接选择目标语言，不出现这个选项，或者再加个设置项以适配这种情况
![image](https://user-images.githubusercontent.com/51697596/139855492-fcaa9598-78fd-4109-872f-ab6785af63f3.png)

**Comment by intellism** [comment]
谢谢反馈
1. 混合语言默认是让翻译引擎自己识别语言的。可能是识别不准确。 如果方便提供样例代码方便场景还原
2. "翻译并替换"，之前是默认翻译目标语言(不用选择)。实际使用过程中，发现替换的时候（国际化场景），不一定是阅读语言，所以增加了替换的目标语言。看看你这边是什么场景，是否有必要省略这一步

**Comment by ltxhhz** [comment]
1. 这是我截图中的注释代码，手动翻译到一半发现弹出的翻译没有翻译成目标语言
``` dart
  /// 获取目录或文件的基本名称。
  ///
  /// 提供 [File], [Directory] 或 [FileSystemEntity] 并将名称返回为 [String].
  ///
  /// ie:
  /// ```dart
  /// controller.basename(dir);
  /// ```
  /// to hide the extension of file, showFileExtension = flase
```

2. 替换的功能我理解您的意思，或许可以考虑下再加个快捷键或者设置项来决定是否弹出语言选择，感激不尽🙏
