### ISSUE TITLE
关于在remote模式（remote-ssh remote-contauner）下无法进行选中翻译，但是ctrl+shift+t可以翻译替换问题

### ISSUE THREAD

**Issue by Osmond1689** [intellism/vscode-comment-translate#74]
也是各种搜索尝试，但是实际问题很简单。。。。。。
写下给其他小伙伴排排坑
      首先明确问题本质，远程环境都不会携带语言的语法高亮配置文件选中翻译依赖语法高亮，所以在远程模式下无法进行选中翻译，ctrl+shift+t可以翻译替换不影响，如果ctrl+shift+t翻译替换都不可以，考虑是否因为墙问题
  
     解决办法：
     额外安装语法高亮
     例如python在远程服务器上安装MagicPython 扩展
     重新加载窗口

![image](https://user-images.githubusercontent.com/59275161/140485280-ba6d9865-6b0c-43be-ab65-46b229b1c3a1.png)

**Comment by Osmond1689** [comment]
不是所有语法高亮扩展都可以，需要尝试和测试，因使用python，所以仅测试了python，最后发现MagicPyhton可以

**Comment by intellism** [comment]
同 #64 相同问题。
