### ISSUE TITLE
《百度源，谷歌源》deepin linux 无法使用，错误提示

### ISSUE THREAD

**Issue by pgy866** [intellism/vscode-comment-translate#75]
![录屏_选择区域_20211109211634](https://user-images.githubusercontent.com/28694676/140932517-06af5bae-96b3-43f0-8ec2-624af6bf242b.gif)

**Comment by intellism** [comment]
你的状态栏线上出了  插件。错误提示应该不是这个插件提醒的。

可以进一步查看下  日志

![image](https://user-images.githubusercontent.com/442894/141057720-e57833f8-a5bc-4f3a-a2be-2ec29b6ab2da.png)

**Comment by yaoying-translation1** [comment]
> 你的状态栏线上小狗插件。错误提示应该不是插件这个提示的。
> 
> 可以进一步查看下日志
> 
> ![图片]


**是此物捣蛋，吾已删除，目前翻译插件仅留vscode-comment-translate**

(https://user-images.githubusercontent.com/442894/141057720-e57833f8-a5bc-4f3a-a2be-2ec29b6ab2da.png)
https://github.com/yanxiaodi/vscode-translator-helper/



但它无论快捷键 或鼠标停留无反应？是何故

**Comment by pgy866** [comment]
> 你的状态栏线上出了 插件。错误提示应该不是这个插件提醒的。
> 
> 可以进一步查看下 日志
> 
> ![图片](https://user-images.githubusercontent.com/442894/141057720-e57833f8-a5bc-4f3a-a2be-2ec29b6ab2da.png)

是此物捣蛋，吾已删除，目前翻译插件仅留vscode-comment-translate
https://github.com/yanxiaodi/vscode-translator-helper/

**但鼠标停留无反应？ 还有其它病态**  只有三健 快捷键有效？能否自定义快捷键  
，或者悬浮显示后在悬浮窗体加一个鼠标点的替换翻译内容
![录屏_dde-desktop_20211116231712](https://user-images.githubusercontent.com/28694676/142014208-c94e89d3-3058-44bf-bad3-ba89111458a8.gif)

**Comment by intellism** [comment]
谢谢反馈，后面陆续优化这部分能力。

1. 划词翻译，，需要鼠标再移动一次，比较麻烦，已经找到方法，划词结束马上出现悬浮提醒。
2. 翻译并替换，需要选择目标语言，另外一个issue也有人提，后面会提供需要选择和直接翻译两个命令。并且hover后浮悬框会增加替换按钮。
3. 命令行设置目标语言，这个算个bug,  后面“保持到workspace”改到“用户”配置。
