### ISSUE TITLE
开启简洁模式后，翻译会失效

### ISSUE THREAD

**Issue by KahnDepot** [intellism/vscode-comment-translate#78]
如题所示，windows环境。

**Comment by KahnDepot** [comment]
我想我应该用一些动图描述这个情况，如下所示：
![bug](https://user-images.githubusercontent.com/81478335/143473786-e1c25344-e5f3-44dd-ab9e-b4c2bbc71309.gif)

**Comment by intellism** [comment]
是没有触发翻译吧，“简洁模式”下需要按住  ctrl/command  hover上去才会触发翻译
