### ISSUE TITLE
加入互译(英<->汉)

### ISSUE THREAD

**Issue by SvenZhao** [intellism/vscode-comment-translate#8]
互译功能:
现在只能选择目标语言 翻译再替换翻译,有时候希望可以实现互译, 例如中<->英

**Comment by intellism** [comment]
互译场景能具个例子吗？ 期望的交互方式是怎么样的

目前插件的核心定位是阅读源码时使用，将源码的(注释)语言转换到自己能理解的语言是第一优先级。

**Comment by SvenZhao** [comment]
我看到插件现在几乎支持所有文件的hover翻译,有些场景下需要做简单的文案国际化,互译到可以提供给我们快速的参考.

**Comment by intellism** [comment]
文案国际化是否可以使用"翻译并替换选择内容"解决。基本上同一时间点，目标语言是明确的

![image](https://user-images.githubusercontent.com/442894/57357468-967fa100-71a5-11e9-8488-bfcbe6998983.png)
