### ISSUE TITLE
 缓存翻译 API 响应以防止速度和 API 速率限制

### ISSUE THREAD

**Issue by cliffordfajardo** [intellism/vscode-comment-translate#80]
为 VSCode 会话期间和之间的持久状态提供有保证的、持久的存储。

这是一个有助于提高翻译速度的建议，也有助于防止使用此扩展程序的人的 API 速率限制。

收到翻译 API 响应后：
   - 将响应保存在 Web 浏览器的 localStorage 中。这种数据缓存很有用，因为很可能有人会多次选择一个词或短语。
     - 这就是我的情况。我下载了一个不同语言的代码库，我经常一遍又一遍地翻译相同的文本，因为我使用这个代码库作为文档
  - 如果所选文本在缓存中，则立即返回它而不是进行 API 调用。
  - 缓存的键可以是选定的文本。

Visual Studio Code (VS Code) 团队有一个模块`Mento` 为在 VS Code 会话之间持久化状态提供了有保障的持久存储
- https://www.chrishasz.com/blog/2020/07/28/vscode-how-to-use-local-storage-api/

**Comment by intellism** [comment]
好建议。添加到计划支持中。

**Comment by intellism** [comment]
v2.0.0 已实现
