### ISSUE TITLE
设置中简洁模式 没有任何描述，用户很难懂

### ISSUE THREAD

**Issue by heartacker** [intellism/vscode-comment-translate#81]
![image](https://user-images.githubusercontent.com/1876302/144740507-dde95b02-208b-4c52-b534-4d0bf2e512ab.png)

ji建议添加更多细节描述，比如
简洁模式，鼠标悬停的时候不显示翻译仅当xxxx 的时候才会显示。

**Comment by intellism** [comment]
实验性功能，按下  ctrl/command 才会触发hover翻译。
运行过程中效果不是特别好，是减少了无效翻译次数，但是对变量等翻译的干扰比较大。

**Comment by intellism** [comment]
v2.0.0已添加描述
