### ISSUE TITLE
**commentTranslate.replaceSelections** 命令失效了

### ISSUE THREAD

**Issue by kiccer** [intellism/vscode-comment-translate#83]
**commentTranslate.replaceSelections** 命令失效了

**Comment by ping003** [comment]
看了下日志，一直提示No selection！

**Comment by kiccer** [comment]
快点修复吧，一直在用旧版😂

**Comment by intellism** [comment]
已修复

**Comment by intellism** [comment]
> 快点修复吧，一直在用旧版😂

可以尝试hover直接翻译替换.

**Comment by kiccer** [comment]
> > 快点修复吧，一直在用旧版😂
> 
> 可以尝试hover直接翻译替换.

我都是同时选中多个选区，一次性翻译的，hover翻译效率太低了
