### ISSUE TITLE
对渲染后的文档进行翻译

### ISSUE THREAD

**Issue by zjns** [intellism/vscode-comment-translate#84]
其实，IntelliJ IDEA平台的翻译插件文档翻译做的很完美，就是这款[TranslationPlugin](https://github.com/YiiGuxing/TranslationPlugin)，能够对渲染后的文档进行翻译，并直接替换原来的文档悬浮窗口显示，支持多种编程语言，像这样
![image](https://user-images.githubusercontent.com/10793522/150078787-7ceb7e14-749c-4459-883d-0d10cdc1f786.png)
不知道VSCode插件能不能实现这样的效果

**Comment by intellism** [comment]
![image](https://user-images.githubusercontent.com/442894/150086836-dfceb4e0-04c7-46e1-b72d-da42c2efab0d.png)
你的意思是直接翻译hover内容吧。之前我也想实现这个能力，目前还没有找到方法。

**Comment by zjns** [comment]
明白了，如果VSCode没提供相应的接口的话，应该是难做的

**Comment by intellism** [comment]
TranslationPlugin 这个插件没有用过，还有什么好的feture，欢迎给建议

**Comment by zjns** [comment]
可惜，官方并不打算支持

**Comment by touchmii** [comment]
> ![image](https://user-images.githubusercontent.com/442894/150086836-dfceb4e0-04c7-46e1-b72d-da42c2efab0d.png)
> 你的意思是直接翻译hover内容吧。之前我也想实现这个能力，目前还没有找到方法。
![Screen Shot 2022-04-23 at 10 03 06 AM](https://user-images.githubusercontent.com/14190567/164863708-347ec974-2d63-43eb-9a1f-72bd1e496506.jpg)

有款叫Code Translate的插件支持悬停翻译，如果鼠标在函数上面会在原有文档后面增加单词翻译，能否读取要翻译的文本翻译之后附加在后面。

**Comment by intellism** [comment]
> 

没有懂你的意思。  是hover里面的内容再追加翻译吗?

**Comment by cubemaze** [comment]
注释翻译  窗口是译文和原文一并显示，能否设置只显示译文呢？ 
![image](https://user-images.githubusercontent.com/117334465/233964064-3975e054-54a8-4321-982d-f7f098c796af.png)

**Comment by intellism** [comment]
> 



> 注释翻译 窗口是译文和原文一并显示，能否设置只显示译文呢？ ![image](https://user-images.githubusercontent.com/117334465/233964064-3975e054-54a8-4321-982d-f7f098c796af.png)

目前还不能隐藏原文, 一直关注找方法中。
