### ISSUE TITLE
[Feature Request]几个关于翻译源与界面的建议

### ISSUE THREAD

**Issue by gahoo** [intellism/vscode-comment-translate#85]
插件很好用。想到几个Feature，可以考虑一下。

1. 快捷键切换下一个翻译源
2. 同时使用多个翻译源翻译并依次列出结果
3. 可选是否以窗格形式展示翻译结果，或添加锁定按钮
4. 增加翻译源https://context.reverso.net/

**Comment by intellism** [comment]
谢谢反馈。

1. 不是特别建议大家频繁切换翻译源，同一翻译源可以增加缓存命中率。   目前已经有切换命令，建议自行绑定快捷键。
2. 增加多个翻译目的还是防止服务不可用。还是希望尽量少请求服务。目前看大部分的质量还可以，所以没必要同列出多个结果
3. 不是特别明白什么意思。麻烦进一步说明
4. 翻译引擎非常多。精力不太够。欢迎PR,可以参考 https://github.com/intellism/deepl-translate 做一个独立翻译源服务插件。
