### ISSUE TITLE
能否预设腾讯云的接口配置

### ISSUE THREAD

**Issue by xiankaiqun** [intellism/vscode-comment-translate#86]
https://cloud.tencent.com/document/product/551/35017
![image](https://user-images.githubusercontent.com/26294948/150719829-23e91697-6a56-4584-99ea-b135d1907f42.png)

**Comment by intellism** [comment]
欢迎PR,可以参考 https://github.com/intellism/deepl-translate，做一个独立翻译源服务插件。

**Comment by xiankaiqun** [comment]
[tencent-cloud-translate](https://marketplace.visualstudio.com/items?itemName=Kaiqun.tencent-cloud-translate)，我已经发布，麻烦您看看有无需要改进的地方

**Comment by xiankaiqun** [comment]
link部分，因为腾讯云并没有一个现成的在线翻译产品，所以我选择跳转到google翻译

**Comment by intellism** [comment]
> link部分，因为腾讯云并没有一个现成的在线翻译产品，所以我选择跳转到google翻译

谢谢支持，亲测可以使用。
可以跳转到google,但是建议链接名称保留 腾讯标识。。否则还以为使用的google源。
![image](https://user-images.githubusercontent.com/442894/154015184-13a79fe1-bf89-4af9-a735-ca25c93cf013.png)
