### ISSUE TITLE
source 是否可以优化为 枚举类型方便用户配置

### ISSUE THREAD

**Issue by heartacker** [intellism/vscode-comment-translate#89]
![image](https://user-images.githubusercontent.com/1876302/154002350-5185730c-cefc-42cf-ac74-f25527213a95.png)

**Comment by intellism** [comment]
source建议用命令更改。。
不能枚举是应为目前支持安装插件扩展source。

![image](https://user-images.githubusercontent.com/442894/154011246-27b26693-948d-4503-ac6d-3f1323bf9d26.png)

![image](https://user-images.githubusercontent.com/442894/154011265-36c652a9-d575-4afa-b450-ed46942e16f3.png)

**Comment by intellism** [comment]
> source建议用命令更改。。 不能枚举是应为目前支持安装插件扩展source。
> 
> ![image](https://user-images.githubusercontent.com/442894/154011246-27b26693-948d-4503-ac6d-3f1323bf9d26.png)
> 
> ![image](https://user-images.githubusercontent.com/442894/154011265-36c652a9-d575-4afa-b450-ed46942e16f3.png)
更改source命令入口非常多，也可以这些地方快捷进入。
![image](https://user-images.githubusercontent.com/442894/154011475-409677ed-e732-44e4-a4b5-e1054efd61ef.png)
![image](https://user-images.githubusercontent.com/442894/154011534-d4a8665f-41d2-4c22-80d3-6f00d7e88794.png)
