### ISSUE TITLE
建议增加禁用状态栏图标的设置

### ISSUE THREAD

**Issue by wtklbm** [intellism/vscode-comment-translate#9]
一般情况下，如果用户仅仅是将一种特定的语言翻译成另一种，而不会用到互转功能的话，那么状态栏的图标就显得多余了，所以建议增加一个设置选项，来让用户选择是否要保留状态栏的功能图标我想这是很棒的。
如果是状态栏非要保留的话，那就缩短一下状态栏的占用空间，毕竟一个状态栏的空间是有限的，如果用户存在多个用到状态栏的扩展，那么状态栏就会出现拥挤，造成的后果就是用户可能出现找不到某个扩展的状态栏图标，如果缩短状态栏的占用，比如只显示一个图标或者比如将"Chinese Simplified" 缩短成"zh-CN"也是一个不错的选择呢

**Comment by intellism** [comment]
很好的建议，后续改为仅显示icon,hover提醒当前目标语言。 可以配置状态栏显示目标语言文本

**Comment by intellism** [comment]
vscode官方出了 隐藏状态栏 功能。 这个需求必要性不高了。
