### ISSUE TITLE
能不能加个自动识别文件所有注释并翻译的功能啊，文件大了一个个翻译很麻烦

### ISSUE THREAD

**Issue by HuangRunQiang** [intellism/vscode-comment-translate#97]
Can you add an automatic recognition of all the annotations and translation function ah, a large file translation is very troublesome

**Comment by intellism** [comment]
谢谢反馈，这个功能可以支持

**Comment by HuangRunQiang** [comment]
> 
现在已经支持了吗还是下一个版本会支持
